### PR TITLE
Separate rosbag_storage from rosbag

### PR DESCRIPTION
**Pull request by dirk-thomas**
Originally filled as #248 by @tfoote

rosbag_storage contains the file manipulation tools but does not depend on the communication libraries. Allowing rosbag to be used at the API level w/o compiling against the communication libraries.

rosbag_storage elements switched to console_bridge from rosconsole

This needs to be paired with: ros/roscpp_core#12

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Manually merged in 63f8fefadba4d80c38cf544cda4556aa3559cb12, e73774f6696892b643be7e71421c375e74401e2b and d6b62d35d827cb2e5e5c22c5449f04603f3c1766 into Hydro only.

**Comment by trainman419** [comment]
Please update the documentation to reflect this split. It is currently nearly impossible to find the documentation for `rosbag::Bag` and `rosbag::View` without knowing that they've been split into a separate package.

**Comment by dirk-thomas** [comment]
The docs now reference the new location: http://docs.ros.org/indigo/api/rosbag/html/c++/

**Comment by trainman419** [comment]
Thanks!

**Pull request closed without merging**
