### PR TITLE
added param, has_param and launch_file substitution arg

### PR DESCRIPTION
**Pull request by xaedes**
added `param`, `has_param` and `launch_file` substitution arg

`param` can substitute ros params
`has_param` can be substituted with bool value whether a ros param exists (e.g. for use in `if` or `unless`)
`launch_file` can be substituted with the name of (one of) the launch file(s) that is parsed until this point, without a given index of which launch file is wanted, the last one is used

also fixed an issue in `_launch_tag` where a ros_config instance where given to the ifunless decorator instead of a context

additionally it is now possible to access `ros_config` for more sophisticated substitution args

### CODE REVIEW

**Comment by progtologist** [comment]
This is a very good functionality for roslaunch.
If I understand correctly, you have implemented loading of arguments using the parameter server, correct?
Will this pull request be merged eventually to groovy and hydro?

**Comment by tfoote** [comment]
roslaunch's API is a core interface for ROS and needs to go through a community review via the REP process. http://www.ros.org/reps/rep-0000.html

**Comment by k-okada** [comment]
+1, param substitution may very useful

**Comment by garaemon** [comment]
+1.
It would be great feature to write re-usable launch file

**Comment by dirk-thomas** [comment]
Closing due to long time of inactivity and targeting an EOL branch. Please consider opening a new PR targeting the current default branch if you are still interested in getting this patch merged.

**Pull request closed without merging**
