### PR TITLE
install advertisetest (#2045)

### PR DESCRIPTION
**Pull request by beetleskin**
**Test Plan:**
- build rostest with install
- source install (from fresh console)
- run `rosrun rostest advertisetest`
- confirm that the node is found (and therefore: confirm that the node is installed properly)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I have retargeted the pull request to `noetic-devel` since patches are only accepted to the latest branch. After it is merged the fix will be backported to `melodic-devel` before the next patch release.

@beetleskin Please rebase your branch on top of `noetic-devel` to resolve conflicts.

**Comment by beetleskin** [comment]
ok, hope this was right?

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Pull request merged**
