### PR TITLE
Replaced deprecated syntax (backticks with repr()).

### PR DESCRIPTION
**Pull request by ajeetdsouza**

### CODE REVIEW

**Comment by ajeetdsouza** [comment]
Any idea why the build fails?

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
Succeeded now. This is an exactly equivalent syntax except that Py3 doesn't support it— see bullet 2 in this list: https://docs.python.org/3.1/whatsnew/3.0.html#removed-syntax

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Pull request merged**
