### PR TITLE
Remove duplicated function, use decorator

### PR DESCRIPTION
**Pull request by eric-wieser**
Requires ros/genpy#52 to be merged/released first, so do not expect tests to pass

### CODE REVIEW

**Comment by eric-wieser** [comment]
ros/genpy#52 is now merged, so this might now pass tests, depending on whether tests use the released version

**Comment by dirk-thomas** [comment]
Yeah, this will require `genpy` to be released. I will retrigger the PR test once this has happened.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
Thanks.

**Pull request merged**
