### PR TITLE
Rosbag Recorder Private-->Protected

### PR DESCRIPTION
**Pull request by DLu**
To enable subclassing of rosbag record behavior.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder please retest this

**Comment by dirk-thomas** [comment]
Currently all this API is internal which means it can be easily changed in future releases. By changing the visibility it is implied that all the API is stable and stays exactly the same.

@ros/ros_team Please review this.

**Comment by gerkey** [comment]
@DLu Can you give more information on your use case? Is there a chance that it could be satisfied via composition instead of inheritance?

**Comment by jackieokay** [comment]
I believe changing functions from private to protected is an ABI change:

https://techbase.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B

I can't speak to the design decision of making Recorder subclassable; in principle it seems fine, but Brian makes a good point that, depending on your design, it might not be the right thing to do.

**Comment by DLu** [comment]
I was exploring solutions to #608 so that I could control (i.e. start and stop) bags from a ROS interface. I ended up just writing a python wrapper, which I consider inelegant in this scenario.

**Comment by wjwwood** [comment]
If there is a use case that needs it, then I think changing them to be protected is ok (potentially some of the members might be left private, but protected should ok too). However, since it is an ABI change I'd prefer it go into Kinetic and not Jade/Indigo.

@DLu do you have a prototype (even a partial one) you could share with us. I'd like to get a sense of what is actually needed for the tool you were discussing. It's clear this class wasn't designed to be inherited from, but maybe we change it in a more subtle way to enable your use case.

**Comment by DLu** [comment]
#706 is another thing I was looking at this functionality for. Unfortunately, I no longer have the prototype I had hacked up.

**Comment by dirk-thomas** [comment]
Should this ticket be closed then?

**Pull request closed without merging**
