### PR TITLE
fix removal of QueuedConnection leading to wrong subscriber count

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addresses #526.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros/ros_team Please review.

**Comment by wjwwood** [comment]
Looks good to me, +1.

Btw, @ros/ros_team doesn't seem to link.

**Comment by dirk-thomas** [comment]
@esteve @tfoote Please review.

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
+1

**Pull request merged**
