### PR TITLE
fixed bug in statistics decision making if one should publish

### PR DESCRIPTION
**Pull request by wentz89**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@wentz89 Please provide at least a minimal description when creating a ticket. In this case the PR aims to fix #1621.

**Comment by kejxu** [comment]
great catch! `time lapsed = 1 / frequency`

> I recognized that pub_frequency_ is a double value, which doesn't make sense

why not, frequency could be a floating point number. and it (implicitly) makes sure `1 / frequency` yields the correct value

**Comment by wentz89** [comment]
@kejxu well yes, but actually no ;). I should have written "it doesn't make sense in this case" cause:
1. the program evaluats a time + Duration(frequenzy), when it should be time + Duration(rate)
2. (but this is my opinion) One usually say this publisher should have a frequency of 100 Hz or 1 Hz or 10 Hz. One never hear 10,5 Hz or 100,7 Hz should be the frequency, therefore it could be an integer value

**Comment by dirk-thomas** [comment]
Thanks for patch.

**Comment by dirk-thomas** [comment]
@wentz89 @kejxu Please see #1577 for a more complete patch for this problem. It would be great if either of you could try that patch and comment on it.

**Pull request merged**
