### PR TITLE
Add __getattr__ to handle sub in message_filters as standard one

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Should `unregister` then be removed?

**Comment by wkentaro** [comment]
Thanks for a good suggestion. I removed `unregister` method.

**Comment by wkentaro** [comment]
Could you please review and merge if it's fine?

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by dirk-thomas** [comment]
Thanks for the contribution.

**Comment by wkentaro** [comment]
Thanks.

**Comment by dirk-thomas** [comment]
It will take quite a while until the patch will be available via Debian packages though. The last `ros_comm` release was just days ago. So the next one will likely be quite some time in the future.

**Comment by wkentaro** [comment]
I see.

**Pull request merged**
