### PR TITLE
removed unused code block

### PR DESCRIPTION
**Pull request by xaedes**
as discussed in 
https://github.com/ros/ros_comm/commit/d59c2c363795c2615b17c22d54cbfe19fccc8044#commitcomment-7947669

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by dirk-thomas** [comment]
@tfoote @wjwwood Please review.

**Comment by wjwwood** [comment]
+1

**Comment by tfoote** [comment]
+1

**Pull request merged**
