### PR TITLE
[rospy] Add rospy.logXXX_once

### PR DESCRIPTION
**Pull request by wkentaro**
Following https://github.com/ros/ros_comm/pull/812

### CODE REVIEW

**Review by dirk-thomas — COMMENTED** [review]
I don't think the `once` logic should be built on top of the `throttle` logic. E.g. there is no call `Time.now` in order to implement `once`.

**Comment by dirk-thomas** [comment]
Thank you. Can you please add the new logging functions to the wiki page mentioning that they are available as of ROS Lunar and post the link to the diff here.

**Comment by wkentaro** [comment]
Updated: http://wiki.ros.org/rospy/Overview/Logging#Logging_Once

**Comment by dirk-thomas** [comment]
Thanks!

**Pull request merged**
