### PR TITLE
Remove duplicate topics from being recorded into one topic

### PR DESCRIPTION
**Pull request by spaghetti-**
Fixes https://github.com/ros/ros_comm/issues/647

### CODE REVIEW

**Comment by wjwwood** [comment]
Seems straight forward to me, and since it's in the cli it shouldn't break any code. However, it does change behavior, so we might want to consider it for release into k-turtle.

**Comment by dirk-thomas** [comment]
The proposed code simply does not do what you describe. E.g. if the vector contain `a b a` the "filtered result is still `a b a` since the code currently only filters consecutive duplicates.

Please also remove the second commit from this PR. That patch was a separate PR which has been merged already.

**Comment by spaghetti-** [comment]
@dirk-thomas good catch thanks, I forgot to sort it. Please call the ci again before you merge thanks!

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by dirk-thomas** [comment]
Thank you for the patch.

Squashed and merged in fac98b93e978974af34badd325eee306e8adfe58.

**Pull request closed without merging**
