### PR TITLE
Test bzfile_ and lz4s_ before reading/writing/closing

### PR DESCRIPTION
**Pull request by jwon02**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for the patch. The other stream implementation seem to lack the same kind of check. Can you update the PR to also add the checking to those.

**Comment by jwon02** [comment]
Okay, let me take a look.

**Comment by jwon02** [comment]
Updated the PR to test lz4s_ before reading and writing.

**Comment by dirk-thomas** [comment]
Can you please also update `uncompressed_stream.cpp`.

**Comment by jwon02** [comment]
I think there is nothing to check for the uncompressed stream.  Did I miss anything?

**Comment by dirk-thomas** [comment]
Same cases checking `ptr` before trying to use it: e.g. https://github.com/ros/ros_comm/blob/cd7efd4d44d0ec5845df7d59ccdfc204389060f2/tools/rosbag_storage/src/uncompressed_stream.cpp#L62

**Update:** never mind - that would be a different kind of check. The uncompressed does indeed not have a file handle what you are checking for the other types.

**Comment by dirk-thomas** [comment]
Same cases checking `ptr` before trying to use it: e.g. https://github.com/ros/ros_comm/blob/cd7efd4d44d0ec5845df7d59ccdfc204389060f2/tools/rosbag_storage/src/uncompressed_stream.cpp#L62

**Update:** never mind - that would be a different kind of check. The uncompressed does indeed not have a file handle what you are checking for the other types.

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Pull request merged**
