### PR TITLE
Fix rosbag API for Python 3

### PR DESCRIPTION
**Pull request by Shevonar**
Closes ros/ros_comm#1047

This commit addresses the remaining issues of #1048.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you please target the branch of @nstiurca with this PR. Then @nstiurca can merge the change into his fork and #1048 can be retested in its updated state.

**Comment by Shevonar** [comment]
I actually don't see the need to involve @nstiurca, as my branch is not forked from his branch and supersedes his changes. Nevertheless I opened nstiurca/ros_comm#1 if it helps the process.

**Comment by dirk-thomas** [comment]
I accidentally assumed your patch was addressing the remaining comment on #1048 but relied on other parts of the patch. Now I see that this patch is "complete" on its own.

I will merge this one as is and close the previous ticket. Thanks and sorry for the extra effort.

**Comment by Shevonar** [comment]
Thanks for merging. I guess my wording in the first comment was missleading.

**Pull request merged**
