### PR TITLE
Remove use of __connection_header in topic_tools relay/throttle and test_roscpp

### PR DESCRIPTION
**Pull request by kwatts**
Topic tools relay and throttle now use the ros::MessageEvent to get connection information. 

The unused (and unbuilt) tool "demux" is removed. 

"test_roscpp" has small changes to use the ros::MessageEvent.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Did you also consider how to update `rosbag` when the `__connection_header` is removed from messages?

Two unit tests are failing for me due to the removal of the connection header:

```
test_rosbag/rosunit-connection_count.xml: 1 tests, 0 errors, 1 failures
test_rosbag/rosunit-latched_sub.xml: 1 tests, 0 errors, 1 failures
```

**Comment by kwatts** [comment]
I can duplicate the latched sub failure on my machine. I'm not sure how it ever worked:

``` python
import rosbag
b = rosbag.Bag('/tmp/test_rosbag_latched_pub.bag', 'r')
conns = [ c for c in b._get_connections() ]
print conns[0].__dict__
# {'datatype': 'std_msgs/String', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'msg_def': 'string data\n\n', 'topic': 'chatter', 
# 'header': {'message_definition': 'string data\n\n', 'md5sum': '992ce8a1687cec8c8bd883ec73ca41d1', 'type': 'std_msgs/String'}, 'id': 0}
```

It looks like the bag file doesn't have the latched field. I'm not sure how old this bag is, it looks like the "latching" field has been there a while. 
http://wiki.ros.org/ROS/Connection%20Header

Any ideas?

**Comment by dirk-thomas** [comment]
All unit tests pass for me and the build farm in hydro. So am I pretty sure the failure is introduced by the changes. I could not fix it yet since I could not figure out which part of the change is responsible.

**Comment by kwatts** [comment]
OK, will look into this. Just to clarify, how do you run the tests using catkin_make?

**Comment by dirk-thomas** [comment]
`catkin_make run_tests`. For the specific cases it is sufficient to run only the test from the _test_rosbag_ package with `catkin_make run_tests_test_rosbag`.

**Comment by kwatts** [comment]
I'm still trying to get my environment set up properly over here. Can we discuss this on Tuesday at our meeting?

**Comment by dirk-thomas** [comment]
The problem is due to this commit: https://github.com/ros/roscpp_core/commit/2de340b4ce152240979d17d43b8f5a7b28002bff
The MessageEvent does not have the connection header information anymore.

**Comment by dirk-thomas** [comment]
Closing incomplete PR in favor of #353.

**Pull request closed without merging**
