### PR TITLE
fix passing multiple args to add_rostest

### LINKED ISSUE #790: add_rostest ARGS only takes the first argument
`add_rostest(test/testlaunchfile.test argument1:=vaule1 argument2:=value2)`

when used in https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rostest/cmake/rostest-extras.cmake.em#L55

generates

``` bash
-- run_tests.py: execute commands
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/efernandez/ws/src/package_name --package=package_name --results-filename test_package_name__argument1_value1.xml --results-base-dir /home/efernandez/ws/build/package_name/test_results /home/efernandez/ws/src/package_name/test/testlaunchfile.test argument1:=value1
  argument2:=value2
```

Note that after the first argument, there's a new line. Maybe that's the problem.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #790.

### CODE REVIEW

**Comment by efernandez** [comment]
:+1: Exactly the fix I was thinking of.

I you give me a few minutes, I can checkout the code and give it a try. Not sure if the tests already check that.

BTW, any chance this could get backported to indigo?

**Comment by dirk-thomas** [comment]
Absolutely, please give it a try and yes, it will be backported since it is a clear bug fix.

**Comment by efernandez** [comment]
@dirk-thomas How can I test it? I've just checkout the repo on my workspace, but it still uses the system version.

**Comment by dirk-thomas** [comment]
After cloning this branch into your workspace and building it other packages in the workspace will use the rostest package from the workspace hence the custom version.

**Comment by efernandez** [comment]
Ok, let me catkin clean && catkin build then (not just catkin build).

**Comment by efernandez** [comment]
Confirmed. It works.

I tested directly with this branch on indigo, which works fine. I guess you'll cherry-pick the commit from this PR into indigo. I guess it'll work too, but please tag me on the PR against indigo if you want me to test it again.

**Comment by dirk-thomas** [comment]
Thanks for testing it.

Since the patch is straight forward I just cherry-picked it to _indigo-devel_: 7f251de8a3a51eb8c03b98944343cbf612e85aff

**Comment by efernandez** [comment]
Thanks for the extremely fast fix.

**Comment by efernandez** [comment]
@dirk-thomas When would the indigo-devel commit get into the next release? :)

**Comment by dirk-thomas** [comment]
While the previous release is in shadow-fixed there are a couple of regressions. So I will likely create a new release in the next days and after a shorter soak time it will be synced (hopefully :wink:).

**Pull request merged**
