### PR TITLE
bugfix: statistics related to #1626 #1621

### PR DESCRIPTION
**Pull request by kikass13**
+ (Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz-- x12 times) performance optimization included

see analysis in #1626 and #1621

From original:
ros_statistics_test_result_original_kinetic_roscpp

Over bugfix:
ros_statistics_test_result_bugfixed_kinetic_roscpp

To Optimization:
ros_statistics_test_result_optimized_kinetic_roscpp

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please target the latest development branch - currently melodic-devel. Also the patch seems to break ABI and as such can only be considered for future ROS distros.

**Comment by dirk-thomas** [comment]
Also please avoid any unrelated changes (e.g. to whitespaces) in the patch as well as don't include statements you used for local debugging.

**Comment by kikass13** [comment]
thanks for your reply, this code is just here so that I can visualize and discuss changes that would be suitable. 

I can obviously remove all the stuff, which is breaking the abi policies (define, added member variables and provide that instead. 
(I will probably do that on Monday)

would such a change be feasible?  what is gonna happen with the kinetic devel branch ... I mean this class is obviously broken since it was created 5 years ago ...

We use kinetic, would these changes be merged back into kinetic as well?  

I mean I would probably have to implement a fixed ros-kinetic roscpp fork inside our code library and jump through the hoops of wrapping the publisher/subscriber classes into a separate namespace ... Just to have access to this statistics feature (which is obviously a must have for every serious system monitoring for autonomous robots).

So my points are: 
 * I need this in kinetic
 * this feature is broken (publish fails after sole time and cpu resources just go nuts for each node * publisher * message_callback 
 * this has to be fast 

thanks for your time :)

**Comment by dirk-thomas** [comment]
> I can obviously remove all the stuff, which is breaking the abi policies (define, added member variables and provide that instead. would such a change be feasible?

Probably yes, but for sure I can only say after reviewing the actual patch.

> what is gonna happen with the kinetic devel branch

A bug fix which is API/ABI compatible can be backported to older distros after it has been applied to the current one.

**Comment by dirk-thomas** [comment]
@kikass13 Friendly ping.

**Comment by kikass13** [comment]
@dirk-thomas this was allready done via #1625 in melodic-devel


https://github.com/ros/ros_comm/blob/3131ac6b1cf78f997653ced9b2f2487075a6d188/clients/roscpp/src/libros/statistics.cpp#L116

**Pull request closed without merging**
