### PR TITLE
Adds stdio Support to rosparam (supercedes #684)

### PR DESCRIPTION
**Pull request by evenator**
I am recreating this PR because the previous one (#684) seems to have broken when I rebased the branch.

`rosparam dump` to stdout is useful for piping the rosparam yaml output to other programs. This PR changes the behavior of `rosparam dump` such that if a user does not specify a filename to the command, `rosparam` will dump to stdout.

`rosparam load` from stdin is useful for piping yaml into rosparam. This PR changes the behavior of `rosparam load` such that if the user specifies "-" as the filename, `rosparam` will load from stdin.

My particular usecase for `rosparam load` from stdin is being able to only load parameters from a launch file:

```
roslaunch robot.launch --dump-params | rosparam load -
```

### CODE REVIEW

**Comment by evenator** [comment]
Ok, I know what's going wrong here, and  fix will be up soon.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by evenator** [comment]
I'll work on fixing these tests (and adding tests for the new functionality) as soon as I get a chance.

**Comment by evenator** [comment]
@dirk-thomas This is ready for review.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please (this time with a rebase)

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please (this time with a rebase)

**Comment by dirk-thomas** [comment]
Can you please resolve the merge conflicts.

**Comment by evenator** [comment]
I merged it. I can rebase if you'd prefer.

**Comment by dirk-thomas** [comment]
Thank you. I squashed the changes and cherry-picked them in 5dcfc8e7437463cbce752e05a969c2e98f7580c6.

**Pull request closed without merging**
