### PR TITLE
[rosbag] Force clock publishing in case of heavy load when playing

### LINKED ISSUE #82: rosbag: Thread publishing time should not block on a read operation
While playing back a bag, rosbag stops publishing clock for variable durations. It's likely that these pauses occur because rosbag cannot read the bag file from NFS quickly enough. Even so, rosbag should continue publishing clock so that other nodes can tell that the bag is still playing.

migration of trac ticket 3321:
  https://code.ros.org/trac/ros/ticket/3321

### PR DESCRIPTION
**Pull request by mikepurvis**
New PR to replace #578, targeting **kinetic-devel**. Fixes #82.

Original PR from @jennan, checking if we still have CI fails here.

### CODE REVIEW

**Comment by mikepurvis** [comment]
Tests have failed on account of the moved bag:

```
00:25:04.154 Scanning dependencies of target download_data_test_clock.bag
00:25:04.242 Downloading http://download.ros.org/data/rosbag/test_clock.bag to /tmp/catkin_workspace/build_isolated/test_rosbag/test/clock.bag... failed (HTTP Error 403: Forbidden)!
00:25:04.290 [100%] Built target download_data_test_clock.bag
```

I verify the 403 locally. @dirk-thomas can you confirm permissions for the file on the OSU server?

**Comment by dirk-thomas** [comment]
~~I have no idea why this changed.~~ Anyway I fixed the permissions on the file - it is downloadable again.

**Update:** never mind - I guess the file was uploaded with the wrong permissions in the first place and that's why the original PR failed the new tests in the first place.

@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
Alas, new failure is a test timeout:

```
00:31:58.971 Scanning dependencies of target _run_tests_test_rosbag_rostest_test_clock_sub_alive.test
00:31:59.038 -- run_tests.py: execute commands
00:31:59.038   /tmp/catkin_workspace/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/tmp/catkin_workspace/src/ros_comm/test/test_rosbag --package=test_rosbag --results-filename test_clock_sub_alive.xml --results-base-dir /tmp/catkin_workspace/test_results /tmp/catkin_workspace/build_isolated/test_rosbag/test/clock_sub_alive.test 
00:31:59.378 ... logging to /home/buildfarm/.ros/log/rostest-568c9b9c2b27-31502.log
00:31:59.555 [ROSUNIT] Outputting test results to /tmp/catkin_workspace/test_results/test_rosbag/rostest-test_clock_sub_alive.xml
00:33:01.025 testclock_sub_alive ... ERROR!
00:33:01.025 ERROR: max time [60.0s] allotted for test [clock_sub_alive] of type [test_rosbag/clock_sub_alive.py]
00:33:01.025   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
00:33:01.025     testMethod()
00:33:01.025   File "/tmp/catkin_workspace/src/ros_comm/tools/rostest/src/rostest/runner.py", line 148, in fn
00:33:01.025     self.test_parent.run_test(test)
00:33:01.025   File "/tmp/catkin_workspace/src/ros_comm/tools/rostest/src/rostest/rostest_parent.py", line 132, in run_test
00:33:01.025     return self.runner.run_test(test)
00:33:01.025   File "/tmp/catkin_workspace/src/ros_comm/tools/roslaunch/src/roslaunch/launch.py", line 681, in run_test
00:33:01.025     (test.time_limit, test.test_name, test.package, test.type))
00:33:01.025 --------------------------------------------------------------------------------
00:33:01.026 
00:33:01.026 [ROSTEST]-----------------------------------------------------------------------
00:33:01.026 
00:33:01.026 
00:33:01.026 SUMMARY
00:33:01.026 [1;31m * RESULT: FAIL[0m
00:33:01.026  * TESTS: 0
00:33:01.026 [1;31m * ERRORS: 1[0m
00:33:01.026  * FAILURES: 0
00:33:01.026 
00:33:01.026 rostest log file is in /home/buildfarm/.ros/log/rostest-568c9b9c2b27-31502.log
00:33:01.154 -- run_tests.py: verify result "/tmp/catkin_workspace/test_results/test_rosbag/rostest-test_clock_sub_alive.xml"
00:33:01.176 [100%] Built target _run_tests_test_rosbag_rostest_test_clock_sub_alive.test
```

I'll have to dig into this locally.

**Comment by simonyilunw** [comment]
any update with this PR? I have been having https://github.com/ros/ros_comm/issues/82 this problem.

@mikepurvis  @dirk-thomas

**Comment by dirk-thomas** [comment]
Closing due to long time of inactivity. Please consider opening a new PR targeting the current default branch if you are still interested in getting this patch merged.

**Pull request closed without merging**
