### PR TITLE
fix roslaunch-check for unreleased wet dependencies (fix #332)

### LINKED ISSUE #332: roslaunch dependency check test looks in manifest.xml for dependency
The `roslaunch_add_file_check` macro complains about missing dependency in manifest.xml file.  It's not clear if the script is looking for the manifest.xml file (in which case it would fail under catkin) or if the dependency is truly missing (which I don't think it is).

The following steps reproduce the problem:
1. Clone the repo:
   `git clone https://github.com/shaun-edwards/industrial_core.git`
   `git checkout rosi_issue_11_launch_test`
2. Make/run the tests:
   `catkin_make run_tests_industrial_robot_simulator`

Resulting output:

```
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /home/ros/ros/release/build/test_results/industrial_robot_simulator
  /opt/ros/hydro/share/roslaunch/cmake/../scripts/roslaunch-check -o /home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml /home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch 
checking *.launch in directory /home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch
checking /home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch/robot_interface_simulator.launch
...writing test results to /home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml
FAILURE:
[/home/ros/ros/release/src/industrial_core/industrial_robot_simulator/launch/robot_interface_simulator.launch]:
    Missing manifest dependencies: industrial_robot_simulator/manifest.xml: industrial_robot_client
wrote test file to [/home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml]
-- run_tests.py: verify result "/home/ros/ros/release/build/test_results/industrial_robot_simulator/roslaunch-check_launch.xml"
```

The test was added to CMakeLists.txt:

```
<snip>
find_package(roslaunch)
roslaunch_add_file_check(launch)
<snip>
```

The package xml has the following depends:

```
<build_depend>industrial_robot_client</build_depend>
<run_depend>industrial_robot_client</run_depend>
```

This appears to be a bug in the roslaunch test macros.

### PR DESCRIPTION
**Pull request by dirk-thomas**
@tfoote @wjwwood Please review.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Not a great way to deal with this but I don't see any non-invasive way to address this.

**Comment by wjwwood** [comment]
+0 bc sucks

**Comment by tfoote** [comment]
+1 since it works

**Comment by shaun-edwards** [comment]
+1, Verified the fix on my end.  Thanks for the quick turn-around.

**Pull request merged**
