### PR TITLE
Fixed Transport constructor getifaddrs memory leak

### PR DESCRIPTION
**Pull request by ghost**
"Get Interface Addresses" allocates memory that is never freed in the Transport constructor.
From the [manpage for getifaddrs](http://man7.org/linux/man-pages/man3/getifaddrs.3.html):
"The data returned by getifaddrs() is dynamically allocated and should be freed using freeifaddrs() when no longer needed."

This turns out to be a serious leak over time, since the number of leaked bytes grows by 1K-2K with every additional Transport invocation. It is even more prevalent in ROS Service Servers, since they are intended to live for a long time and accept multiple connections. For the following tests, I am showing pub/sub for simplicity. Note that after the patch, **definitely lost** drops down to 0 bytes.

Thanks to @rethink-dcookson for uncovering this issue.
#### Test Environment Setup
- sourcing a typical indigo setup.bash
- checking out ros_comm, ros_comm_msgs, and ros_tutorials repos
- building with catkin & sourcing devel/setup.bash
- running roscore, talker, and listener with valgrind (in separate sourced terminals)
#### Pre-Patch Test (ROS Topic)

```
$ roscore
```

```
$ valgrind --tool=memcheck --leak-check=yes  --log-file=talker4.log ./talker
...
==25866== 1,748 bytes in 1 blocks are definitely lost in loss record 52 of 54
==25866==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25866==    by 0x609C687: getifaddrs_internal (ifaddrs.c:402)
==25866==    by 0x609D1EF: getifaddrs (ifaddrs.c:825)
==25866==    by 0x50EAE5D: ros::Transport::Transport() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F17AB: ros::TransportTCP::TransportTCP(ros::PollSet*, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
...
==25866== 1,748 bytes in 1 blocks are definitely lost in loss record 53 of 54
==25866==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25866==    by 0x609C687: getifaddrs_internal (ifaddrs.c:402)
==25866==    by 0x609D1EF: getifaddrs (ifaddrs.c:825)
==25866==    by 0x50EAE5D: ros::Transport::Transport() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50EB8D2: ros::TransportUDP::TransportUDP(ros::PollSet*, int, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
...
==25866== 3,496 bytes in 2 blocks are definitely lost in loss record 54 of 54
==25866==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25866==    by 0x609C687: getifaddrs_internal (ifaddrs.c:402)
==25866==    by 0x609D1EF: getifaddrs (ifaddrs.c:825)
==25866==    by 0x50EAE5D: ros::Transport::Transport() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F17AB: ros::TransportTCP::TransportTCP(ros::PollSet*, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F6E1C: ros::TransportTCP::accept() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F7248: ros::TransportTCP::socketUpdate(int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F89B2: boost::_mfi::mf1<void, ros::TransportTCP, int>::operator()(ros::TransportTCP*, int) const (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F8777: void boost::_bi::list2<boost::_bi::value<ros::TransportTCP*>, boost::arg<1> >::operator()<boost::_mfi::mf1<void, ros::TransportTCP, int>, boost::_bi::list1<int&> >(boost::_bi::type<void>, boost::_mfi::mf1<void, ros::TransportTCP, int>&, boost::_bi::list1<int&>&, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F8669: void boost::_bi::bind_t<void, boost::_mfi::mf1<void, ros::TransportTCP, int>, boost::_bi::list2<boost::_bi::value<ros::TransportTCP*>, boost::arg<1> > >::operator()<int>(int&) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x50F8520: boost::detail::function::void_function_obj_invoker1<boost::_bi::bind_t<void, boost::_mfi::mf1<void, ros::TransportTCP, int>, boost::_bi::list2<boost::_bi::value<ros::TransportTCP*>, boost::arg<1> > >, void, int>::invoke(boost::detail::function::function_buffer&, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25866==    by 0x5139DC9: boost::function1<void, int>::operator()(int) const (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
...
==25866== LEAK SUMMARY:
==25866==    definitely lost: 6,992 bytes in 4 blocks
==25866==    indirectly lost: 0 bytes in 0 blocks
==25866==      possibly lost: 788 bytes in 15 blocks
==25866==    still reachable: 3,376 bytes in 39 blocks
==25866==         suppressed: 0 bytes in 0 blocks
```

```
$ valgrind --tool=memcheck --leak-check=yes --log-file=listener.log ./listener
...
==25868== 1,748 bytes in 1 blocks are definitely lost in loss record 52 of 55
==25868==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25868==    by 0x5E71687: getifaddrs_internal (ifaddrs.c:402)
==25868==    by 0x5E721EF: getifaddrs (ifaddrs.c:825)
==25868==    by 0x50EAE5D: ros::Transport::Transport() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x50F17AB: ros::TransportTCP::TransportTCP(ros::PollSet*, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
...
==25868== 1,748 bytes in 1 blocks are definitely lost in loss record 53 of 55
==25868==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25868==    by 0x5E71687: getifaddrs_internal (ifaddrs.c:402)
==25868==    by 0x5E721EF: getifaddrs (ifaddrs.c:825)
==25868==    by 0x50EAE5D: ros::Transport::Transport() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x50EB8D2: ros::TransportUDP::TransportUDP(ros::PollSet*, int, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
...
==25868==    by 0x4114E4: main (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/roscpp_tutorials/listener)
==25868== 1,748 bytes in 1 blocks are definitely lost in loss record 54 of 55
==25868==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25868==    by 0x5E71687: getifaddrs_internal (ifaddrs.c:402)
==25868==    by 0x5E721EF: getifaddrs (ifaddrs.c:825)
==25868==    by 0x50EAE5D: ros::Transport::Transport() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x50F17AB: ros::TransportTCP::TransportTCP(ros::PollSet*, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x50F6E1C: ros::TransportTCP::accept() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x50F7248: ros::TransportTCP::socketUpdate(int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
...
==25868== 1,748 bytes in 1 blocks are definitely lost in loss record 55 of 55
==25868==    at 0x4C2CC70: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25868==    by 0x5E71687: getifaddrs_internal (ifaddrs.c:402)
==25868==    by 0x5E721EF: getifaddrs (ifaddrs.c:825)
==25868==    by 0x50EAE5D: ros::Transport::Transport() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x50F17AB: ros::TransportTCP::TransportTCP(ros::PollSet*, int) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x51236B6: ros::Subscription::pendingConnectionDone(boost::shared_ptr<ros::Subscription::PendingConnection> const&, XmlRpc::XmlRpcValue&) (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x5127711: ros::Subscription::PendingConnection::check() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
==25868==    by 0x509194F: ros::XMLRPCManager::serverThreadFunc() (in /data/users/imcmahon/Development/test_ws/test_ros_comm_leak_ws/devel/lib/libroscpp.so)
...
==25868== LEAK SUMMARY:
==25868==    definitely lost: 6,992 bytes in 4 blocks
==25868==    indirectly lost: 0 bytes in 0 blocks
==25868==      possibly lost: 788 bytes in 15 blocks
==25868==    still reachable: 3,376 bytes in 39 blocks
==25868==         suppressed: 0 bytes in 0 blocks
```
#### Post-Patch Test (ROS Topic)

```
$ roscore
```

```
$ valgrind --tool=memcheck --leak-check=yes  --log-file=talker.log ./talker
...
==24757==    by 0x4085ED: main (in /data/users/imcmahon/Development/test_ws/test_ros_comm_ws/devel/lib/roscpp_tutorials/talker)
==24757==
==24757== LEAK SUMMARY:
==24757==    definitely lost: 0 bytes in 0 blocks
==24757==    indirectly lost: 0 bytes in 0 blocks
==24757==      possibly lost: 788 bytes in 15 blocks
==24757==    still reachable: 3,376 bytes in 39 blocks
==24757==         suppressed: 0 bytes in 0 blocks
```

```
$ valgrind --tool=memcheck --leak-check=yes --log-file=listener.log ./listener
...
==24741==    by 0x4114E4: main (in /data/users/imcmahon/Development/test_ws/test_ros_comm_ws/devel/lib/roscpp_tutorials/listener)
==24741==
==24741== LEAK SUMMARY:
==24741==    definitely lost: 0 bytes in 0 blocks
==24741==    indirectly lost: 0 bytes in 0 blocks
==24741==      possibly lost: 788 bytes in 15 blocks
==24741==    still reachable: 3,376 bytes in 39 blocks
==24741==         suppressed: 0 bytes in 0 blocks
```

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for the PR. It will take some time until we will can review and merge it.

**Comment by rethink-imcmahon** [comment]
Thanks for taking a look at this, Dirk. As @rethink-rlinsalata pointed out to me today, transport.cpp is not the only place getifaddrs() / freeifaddrs() is used in this repo. This pull request is just bringing transport.cpp in sync with [network.cpp](https://github.com/ros/ros_comm/blob/ce75bf8d9c19f8337d2196d3d19f9ba8745e0583/clients/roscpp/src/libros/network.cpp#L126-L164)

**Comment by wjwwood** [comment]
@grieneis this is on @dirk-thomas's todo list to review and merge. I'll also try to give it a review as well in the short term.

**Comment by wjwwood** [comment]
+1 Looks good to me.

We are maintaining the original pointer from `getifaddrs` and freeing that, using a separate pointer for iterating through the addresses, which is correct. And the official examples don't seem to indicate that freeing is required when there is an error with `getifaddrs`, but the man page doesn't explicitly state it one way or the other.

**Comment by jcornier** [comment]
Hi ,

I also have the same problem after 1hour my application crash because I have to much memory in used. The only available solution is to get sources of ros_comm package an apply the patch?

Tks

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by dirk-thomas** [comment]
@rethink-imcmahon I reviewed the code and as far as I can see the patch is complete. The function `getifaddrs` is only called in two locations in this repo.

In the file `network.cpp` `freeifaddrs` it is invoked correctly to free the memory. And this PR adds the missing invocation to the file `transport.cpp`. All further references are only in strings and comments. Therefore I don't think anything else needs patching beyond this PR.

**Comment by dirk-thomas** [comment]
The memory leak is a regression of #452 (@codebot  FYI) and therefore only affects the _indigo-devel_ branch.

**Comment by jcornier** [comment]
To resolve this problem is checkout the code of the ros_comm package using:

> rosco ros_comm
> I update the file transport.cpp
> An il recompile it in my workspace. The memory leak problem seams to be resolved.
> Is it the correct way to ? (probably not)

Sorry for my question but I'm new in ROS so i don't all mechanism available;

Tks for helping

**Comment by dirk-thomas** [comment]
@jcornier Yes, that is the correct way to overlay an installed package with a newer version of the package built from source. Just remember to remove the source package from the workspace again once you have installed the to-be-released new version from Debian.

**Comment by jcornier** [comment]
Ok so until a new release of ROS with the Fix is not available I need to keep the source and binaries in my workspace in order to overlay the default version of the package installed in /opt/ros/indigo . That's correct?

**Comment by rethink-imcmahon** [comment]
@jcornier Yup! Until the next Indigo release, that's the way to patch locally.

@wjwwood and @dirk-thomas, fantastic! Thanks for reviewing & merging.

**Comment by BennyRe** [comment]
Is this fix already in the debs? I still get getifaddrs leaks.

**Comment by maxikrie** [comment]
I also still have this problem.

**Comment by dirk-thomas** [comment]
When you click on the commit referenced (1df83085f88313bfe3cc6510690726939b157772) above which fixed the problem you see that it is available in the tag _1.11.11_. This version has been released very recently and it still takes time until the Debian package will be available (http://www.ros.org/debbuild/indigo.html?q=roscpp).

**Pull request merged**
