### PR TITLE
Backport "Unable to report rosout: __exit__" fix to ROS Melodic

### PR DESCRIPTION
**Pull request by mm318**
This is a backport of https://github.com/ros/ros_comm/pull/1915 to `melodic-devel`.

### CODE REVIEW

**Comment by mm318** [comment]
Hi @dirk-thomas and @chapulina, this is the pull request for backporting https://github.com/ros/ros_comm/pull/1915. If this is redundant or not the right process for backporting, then please close this pull request.

**Comment by mm318** [comment]
Hi @dirk-thomas and @chapulina, this pull request should be ready to be merged. Thanks.

**Comment by dirk-thomas** [comment]
We don't backport individual patches like this since it becomes impossible to track what has / hasn't been backported and why.

Please see #1917 which include this backport.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-melodic-sync-2020-03-20/13306/1

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/new-packages-for-melodic-2020-03-22/13329/5

**Pull request closed without merging**
