### PR TITLE
Use boost::make_shared instead of new for constructing shared_ptrs

### PR DESCRIPTION
**Pull request by kartikmohta**
As per https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rh-make_shared

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros/ros_team Please review this.

**Comment by wjwwood** [comment]
Seems low risk to me. I would classify it as somewhat unnecessary though, because it isn't functionally different.

+1 to merge at the next convenient time

Thanks @kartikmohta!

**Comment by dirk-thomas** [comment]
Thank you for the patch. I have squashed and merge the changes in 90b0eb7519a761bfa8c102ceb954c6fb9df57a4a

**Pull request closed without merging**
