### PR TITLE
Fix migration rule

### PR DESCRIPTION
**Pull request by efernandez**
This PR is on top of https://github.com/ros/ros_comm/pull/1010 and fixes the test provided there.

This also replaces https://github.com/ros/ros_comm/pull/996

@mikepurvis @dirk-thomas 

FYI @afakihcpr @servos

### CODE REVIEW

**Comment by efernandez** [comment]
@dirk-thomas FYI I've locally seen this unrelated test (https://github.com/ros/ros_comm/blob/lunar-devel/test/test_rosbag/test/test_bag.py#L328) failing intermittently:

``` bash
$ make run_tests_test_rosbag_nosetests_test.test_bag.py
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /home/eperdomo/dev/ws/clearpath_ws/build/test_rosbag/test_results/test_rosbag
  /usr/bin/nosetests-2.7 -P --process-timeout=60 /home/eperdomo/dev/ws/clearpath_ws/src/ros_comm/test/test_rosbag/test/test_bag.py --with-xunit --xunit-file=/home/eperdomo/dev/ws/clearpath_ws/build/test_rosbag/test_results/test_rosbag/nosetests-test.test_bag.py.xml
 /tmp/test_rosbag_filter__2.bag                                                                                                               100%              6.2 KB 00:00    
 /tmp/tmpsCAnH2/test_rosbag_filter__2.bag                                                                                                     100%              7.5 KB 00:00    
 /tmp/tmpsCAnH2/test_rosbag_filter__3.bag                                                                                                     100%              7.5 KB 00:00    
...
======================================================================
FAIL: test_get_compression_info (test_bag.TestRosbag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eperdomo/dev/ws/clearpath_ws/src/ros_comm/test/test_rosbag/test/test_bag.py", line 328, in test_get_compression_info
    self.assertGreater(info.compressed, 900)
AssertionError: 900 not greater than 900

----------------------------------------------------------------------
Ran 18 tests in 4.223s

FAILED (failures=1)
-- run_tests.py: verify result "/home/eperdomo/dev/ws/clearpath_ws/build/test_rosbag/test_results/test_rosbag/nosetests-test.test_bag.py.xml"
Built target run_tests_test_rosbag_nosetests_test.test_bag.py
```

``` bash
$ make run_tests_test_rosbag_nosetests_test.test_bag.py
-- run_tests.py: execute commands
  /usr/bin/cmake -E make_directory /home/eperdomo/dev/ws/clearpath_ws/build/test_rosbag/test_results/test_rosbag
  /usr/bin/nosetests-2.7 -P --process-timeout=60 /home/eperdomo/dev/ws/clearpath_ws/src/ros_comm/test/test_rosbag/test/test_bag.py --with-xunit --xunit-file=/home/eperdomo/dev/ws/clearpath_ws/build/test_rosbag/test_results/test_rosbag/nosetests-test.test_bag.py.xml
 /tmp/test_rosbag_filter__2.bag                                                                                                               100%              6.2 KB 00:00    
 /tmp/tmpGOevHQ/test_rosbag_filter__2.bag                                                                                                     100%              7.5 KB 00:00    
 /tmp/tmpGOevHQ/test_rosbag_filter__3.bag                                                                                                     100%              7.5 KB 00:00    
...
----------------------------------------------------------------------
Ran 18 tests in 4.221s

OK
-- run_tests.py: verify result "/home/eperdomo/dev/ws/clearpath_ws/build/test_rosbag/test_results/test_rosbag/nosetests-test.test_bag.py.xml"
Built target run_tests_test_rosbag_nosetests_test.test_bag.py
```

These are two consecutive runs. I've seen values as low as `889`. Let me know if you want me to reduce the lower bound to `888`.

Either way, this and the others tests pass for this PR.

**Comment by efernandez** [comment]
Now that https://github.com/ros/ros_comm/pull/1009 is merged, I've just rebased both https://github.com/ros/ros_comm/pull/1010 and https://github.com/ros/ros_comm/pull/1011 on top of `lunar-devel`, so they can be reviewed.

I recommend reviewing the test on https://github.com/ros/ros_comm/pull/1010 and here only the two latest commits, which only bring a fairly minimal change compared to the test.
Remember that https://github.com/ros/ros_comm/pull/1010 is up only for reviewing and showing the current logic fails with the new test. We should close that PR after the review and merge only https://github.com/ros/ros_comm/pull/1011.

Thanks!

**Comment by dirk-thomas** [comment]
@efernandez This looks good to me. Does it make sense to squash the last two commits?

@mikepurvis What do you think? Did you run this code as part of your testing?

**Comment by efernandez** [comment]
@dirk-thomas I think they cover two different things:

1. https://github.com/ros/ros_comm/pull/1011/commits/045b7b1f3cbe6920fa749c98ed7b8b4127945111 is the main fix for the new test case. It checks for a path directly to the last message first.
2. https://github.com/ros/ros_comm/pull/1011/commits/bb71941a808dea0a7a9f11960818a00b4a8630db adds a premature check for sub-rules, so it allows to check more options if the sub-rules fail. Before, the first option with the top rules valid was picked, regardless of the sub-rules. With this commit, the premature check allows to discard options that would fail due to the sub-rules, and therefore check other options. This is an improvement in the line of this comment: https://github.com/clearpathrobotics/ros_comm/blob/bb71941a808dea0a7a9f11960818a00b4a8630db/tools/rosbag/src/rosbag/migration.py#L307

Regarding testing, @mikepurvis cherry-picked the last two commits (not the test stuff because it wasn't implemented by that time) and get it into the bundles we run on our robots https://github.com/ros/ros_comm/commits/lunar-edge (that has this commit https://github.com/ros/ros_comm/commit/4c4358f61410fbafd68d9078f7520d2cfa4dc550, with the two fix commits from here). That's been running now for approximately 1 month with a message that needs the migration fix from this PR. Migration is done on the fly using the rosbag migration (Python) API.

**Comment by dirk-thomas** [comment]
@efernandez Thanks for the explanation. Sounds good to me.

**Comment by dirk-thomas** [comment]
Would you like to see these changes (including the ones from the previous PR) backported (and if yes, wo which ROS distros) or do you not mind since you use a fork anyway?

**Comment by mikepurvis** [comment]
We are running from `lunar-devel`/`lunar-edge` now, so no need for backport from our side.

**Comment by efernandez** [comment]
Exactly, no need to backport.

And regarding public ROS packages with changed messages, there are only two AFAIK. One of them is this one:

``` bash
trajectory_msgs$ l rules/
JointTrajectoryPoint_Groovy2Hydro_08.10.2013.bmr
```

**Pull request merged**
