### PR TITLE
changed docstring to reflect behaviour of read_messages()

### PR DESCRIPTION
**Pull request by spaghetti-**
fixes https://github.com/ros/ros_comm/issues/618

### CODE REVIEW

**Comment by wjwwood** [comment]
Seems the consensus of #618 was not only to update the docs but also change how empty lists are handled. @dlaz might want to comment on this.

**Comment by dlaz** [comment]
Until how empty lists are handled is changed, I think it makes sense to update the docstring to reflect the actual behavior.

**Comment by spaghetti-** [comment]
@wjwwood however that will also change behavior which we may not want to introduce abruptly.

**Comment by dirk-thomas** [comment]
Thanks.

**Pull request merged**
