### PR TITLE
fix unknown msg-generation dependency

### PR DESCRIPTION
**Pull request by rhaschke**
cmake complains:

> The dependency target "rosgraph_msgs_genpy" of target "double_pub" does not exist.

msg dependencies should be pulled in with EXPORTED_TARGETS variable.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The PR contains additional unrelated commit. Can you please remove them so that this only changes the CMake target dependency.

**Comment by tfoote** [comment]
@ros-pull-request-builder retest this please

**Comment by rhaschke** [comment]
> The PR contains additional unrelated commit. Can you please remove them so that this only changes the CMake target dependency.

Ups. Fixed.

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Pull request merged**
