### PR TITLE
[kinetic] Exclude unused args check if pass_all_args is set

### LINKED ISSUE #889: roslaunch: pass_all_args exception if there are extra args defined
I just tried using this attribute on a fairly complex launch file that has multiple `<arg>`s declared, and it leads to an exception because not all of the `<arg>`s are defined in the `<include>`d file.

For example, in the `drcsim_gazebo` package, [atlas.launch](https://bitbucket.org/osrf/drcsim/src/194be8500fef81593f79607a21ee2badd9700a0e/drcsim_gazebo/launch/atlas.launch?at=default&fileviewer=file-view-default#atlas.launch-14) includes [atlas_no_controllers.launch](https://bitbucket.org/osrf/drcsim/src/194be8500fef81593f79607a21ee2badd9700a0e/drcsim_gazebo/launch/atlas_no_controllers.launch?at=default&fileviewer=file-view-default) and passes three arguments. I removed some of the duplicate argument definitions in [this commit](https://bitbucket.org/osrf/drcsim/commits/d5c93d7db649ca4df6c07d6fcba6f9e77953913a), but roslaunch gives an exception since there are extra `<arg>`s in `atlas.launch` that aren't part of `atlas_no_controllers.launch` (for example, [inertia_args](https://bitbucket.org/osrf/drcsim/src/194be8500fef81593f79607a21ee2badd9700a0e/drcsim_gazebo/launch/atlas.launch?at=default&fileviewer=file-view-default#atlas.launch-8)).

I'm guessing this will be close as a "won't fix", but I wanted to mention it since I was excited when @gerkey added this feature in #710, but now there's quite a few instances when I won't be able to use it.

### PR DESCRIPTION
**Pull request by v-lopez**
* Exclude unused args check if pass_all_args is set

* Add test for pass_all_args fix

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Proposed backport of #1520. Will likely be handle in a PR collecting all patches for backporting instead...

**Comment by 130s** [comment]
@ros-pull-request-builder retest this please

**Comment by msmcconnell** [comment]
Any updates on this backport being included anytime soon?

**Comment by maracuya-robotics** [comment]
Can we get this simple change merged, please?

**Comment by dirk-thomas** [comment]
The original fix hasn't been released into Melodic yet (which will happen soon). After that all changes from the `melodic-devel` branch will be considered for backporting to `kinetic-devel`. Therefore closing this as a duplicate.

**Pull request closed without merging**
