### PR TITLE
Added const versions of XmlRpcValue converting operators.

### PR DESCRIPTION
**Pull request by peci1**
Followup of https://github.com/ros/ros_comm/pull/1759.

### CODE REVIEW

**Comment by peci1** [comment]
It'd also be possible to return copies of the data instead of references when called on the const object. That might make some downstream code a little nicer, but const references seem to me like more versatile (or performance-friendly if ever anybody is interested in the performance of this library).

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Comment by peci1** [comment]
Thanks. That was lightning fast :) Is this eligible for backporting?

**Comment by dirk-thomas** [comment]
> Is this eligible for backporting?

Sounds reasonable to me. I assumed it is API and ABI compatible so no problem to backport it before the next Melodic patch release.

**Pull request merged**
