### PR TITLE
rosbag record: Add TransportHint options --tcpnodelay and --udp

### PR DESCRIPTION
**Pull request by alspitz**

### CODE REVIEW

**Comment by romainreignier** [comment]
I have tested this PR, it works well and should be merged I think.

Recording messages at 200Hz, they were packed and the replay was erroneous. Now it simply works.

**Comment by dirk-thomas** [comment]
Thank you for contributing this patch.

Since it changes ABI I will mark it to be included in the next ROS distro which will be Melodic.

**Comment by ArekSredzki** [comment]
@dirk-thomas Could this change please be backported to kinetic? It would be remarkably useful.

**Comment by mikepurvis** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
The Debian stretch failures are known (#1358), but the subPub failure looks new, and it happened twice in a row. Not obvious to me what's going on with it though:

```11:16:43 Scanning dependencies of target _run_tests_test_roscpp_rostest_test_launch_pingpong.xml
11:16:43 -- run_tests.py: execute commands
11:16:43   /tmp/catkin_workspace/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/tmp/catkin_workspace/src/ros_comm/test/test_roscpp --package=test_roscpp --results-filename test_launch_pingpong.xml --results-base-dir /tmp/catkin_workspace/test_results /tmp/catkin_workspace/src/ros_comm/test/test_roscpp/test/launch/pingpong.xml 
11:16:44 ... logging to /home/buildfarm/.ros/log/rostest-056929760d0f-24788.log
11:16:44 [ROSUNIT] Outputting test results to /tmp/catkin_workspace/test_results/test_roscpp/rostest-test_launch_pingpong.xml
11:16:56 [Testcase: testpingpong] ... ok
11:16:56 
11:16:56 [ROSTEST]-----------------------------------------------------------------------
11:16:56 
11:16:56 [test_roscpp.rosunit-pingpong/subPub][FAILURE]----------------------------------
11:16:56 /tmp/catkin_workspace/src/ros_comm/test/test_roscpp/test/src/sub_pub.cpp:126
11:16:56 Failed
11:16:56 --------------------------------------------------------------------------------
11:16:56 
11:16:56 
11:16:56 SUMMARY
11:16:56 [1;31m * RESULT: FAIL[0m
11:16:56  * TESTS: 1
11:16:56  * ERRORS: 0
11:16:56 [1;31m * FAILURES: 1[0m
11:16:56 
11:16:56 rostest log file is in /home/buildfarm/.ros/log/rostest-056929760d0f-24788.log
11:16:56 -- run_tests.py: verify result "/tmp/catkin_workspace/test_results/test_roscpp/rostest-test_launch_pingpong.xml"
11:16:56 [100%] Built target _run_tests_test_roscpp_rostest_test_launch_pingpong.xml
11:16:56 Scanning dependencies of target _run_tests_test_roscpp_rostest_test_launch_namespaces.xml```

In any case, I can't imagine it's related to this change, since the test has nothing to do with rosbag.

**Comment by mikepurvis** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
Looks great, thanks!

**Pull request merged**
