### PR TITLE
Test for publisher impl deregister leak

### PR DESCRIPTION
**Pull request by mvollrath**
This is a test for #661

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by mvollrath** [comment]
Something's wrong, should be failing.  Giving it another go.

**Comment by mvollrath** [comment]
I don't know why it's not failing, I am running the test with `rostest ~/ros_comm_ws/src/ros_comm/test/test_rospy/test/rostest/deregister.test`

**Comment by mvollrath** [comment]
The PR test doesn't run rostests.  What to do?  I think that a node has to be init to really test this, but I'll try a unit test anyway.

**Comment by dirk-thomas** [comment]
Looking at the console ouput it did run the test: http://jenkins.ros.org/job/_pull_request-indigo-ros_comm/386/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/consoleFull (search for `test_deregister.test`). The output is kind of tough to read since multiple tests are run concurrently to the output gets all mixed up.

```
[test_rospy.rosunit-rospy_deregister/test_unpublish][FAILURE]-------------------
<rospy.topics._PublisherImpl object at 0x2b21e7323990> is not None
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/rosbuild/hudson/workspace/_pull_request-indigo-ros_comm/ARCH_PARAM/amd64/UBUNTU_PARAM/trusty/label/devel/src_repository/monitored_vcs/test/test_rospy/test/rostest/test_deregister.py", line 109, in test_unpublish
    self.assertIsNone(impl())
  File "/usr/lib/python2.7/unittest/case.py", line 956, in assertIsNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 412, in fail
    raise self.failureException(msg)
```

I don't know why Jenkins does not pick up the failing test though :disappointed:

**Comment by mvollrath** [comment]
We've seen this problem too, catkin_test_results does not find rostest results because the xml is mangled iirc.

**Comment by dirk-thomas** [comment]
It does look like it is neither Jenkins nor catkin_test_results fault. I ran the test locally (without the patch) and it clearly fails according to the console output. But the generated xml result file only contains one succeeding test and the output of the roslaunch invocation. The system-out actually contains this snippet:

```
[ROSTEST]test [rospy_deregister] finished
[ROSTEST]test [rospy_deregister] results are in [/home/dthomas/.ros/test_results/test_rospy/rosunit-rospy_deregister.xml]
[ROSTEST]test [rospy_deregister] results summary: 0 errors, 1 failures, 3 tests
```

But from Jenkins point of view (or catkin_test_results) there are no failing tests. This looks like a problem in `rostest`...

The Jenkins view truncates the system-out by default that's why it is not visible in http://jenkins.ros.org/job/_pull_request-indigo-ros_comm/386/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/testReport/rostest.runner/RosTest/testrospy_deregister/
The above snippet is basically hidden in this block: `...[truncated 1125 chars]...`

**Comment by dirk-thomas** [comment]
I will track the test reporting problem in #668 and go ahead merging this as well as the corresponding patch.

Thanks!

**Pull request merged**
