### PR TITLE
roslaunch: add --log option

### PR DESCRIPTION
**Pull request by k-okada**
add --log option which force all node output to log, Useful when you store all information in log file

### CODE REVIEW

**Comment by mikepurvis** [comment]
FYI @guillaumeautran

**Comment by mikepurvis** [comment]
Looks reasonable and non-harmful. Thanks for the contribution!

**Comment by mikepurvis** [comment]
Please add a note to the following wiki page about the new functionality: http://wiki.ros.org/roslaunch/Commandline%20Tools

**Comment by k-okada** [comment]
@mikepurvis ok, updated the wiki http://wiki.ros.org/roslaunch/Commandline%20Tools#preview

**Comment by dirk-thomas** [comment]
I marked the new option with "New in Melodic": http://wiki.ros.org/action/diff/roslaunch/Commandline%20Tools?action=diff&rev1=50&rev2=51

**Pull request merged**
