### PR TITLE
Promote the result of read_messages to a namedtuple

### PR DESCRIPTION
**Pull request by eric-wieser**
Which is backwards compatible

### CODE REVIEW

**Comment by eric-wieser** [comment]
This strikes me as an unrelated test failure

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by eric-wieser** [comment]
Does that only work if you say it?

**Comment by dirk-thomas** [comment]
Yes, you need to be admin on the orgunit for Jenkins to "accept" the magic phrases of the GitHubPullRequestBuilder plugin.

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Comment by dirk-thomas** [comment]
Cherry-picked to _kinetic-devel_ in: 1ee3fde8f873b45fcf53a3cec54723a137a0560f

**Pull request merged**
