### PR TITLE
Fixed g++ 7 fall through warnings

### PR DESCRIPTION
**Pull request by racko**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Maybe this should use a `-Wimplicit-fallthrough=4` compliant comment. I would suggest `// lint -fallthrough` since it makes it also clear that the comments purpose is related to linting.

**Comment by racko** [comment]
```
11:06:13 [test_rosbag.rosunit-r03random_play/test_random_play][FAILURE]------------------
11:06:13 False is not true
11:06:13   File "/usr/lib/python2.7/unittest/case.py", line 329, in run
11:06:13     testMethod()
11:06:13   File "/tmp/catkin_workspace/src/ros_comm/test/test_rosbag/bag_migration_tests/test/random_play.py", line 155, in test_random_play
11:06:13     self.assertTrue(abs(input_time - expect_time) < .5)
11:06:13   File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
11:06:13     raise self.failureException(msg)
```

Let's check if I can retrigger the test :)

**Comment by racko** [comment]
@ros-pull-request-builder retest this please

**Comment by racko** [comment]
bump

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Pull request merged**
