### PR TITLE
Fix segmentation fault on OS X 10.9 (clang / libc++)

### PR DESCRIPTION
**Pull request by NikolausDemmel**
Accessing front() of an empty std::deque is undefined behavior.
With gcc/libstdc++ it seems fine, on clang / libc++ it causes a segmentation fault.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Looks good to me +1
Thanks for the patch.

**Comment by NikolausDemmel** [comment]
Thanks for merging. I should have mentioned that I only did limited testing, and that even only on OS X 10.9.

**Comment by dirk-thomas** [comment]
Please mention this next time you create a pull request.

But in this case the patch only delays the fetching of the elements until they are actually needed. And since the `front()` function has not side effects I am pretty confident that it won't break anything. But the CI job on Jenkins will tell us if we are wrong.

**Comment by NikolausDemmel** [comment]
Yes, sorry for not mentioning it clearly. I don't have a setup where I can easily test more than OS X 10.9 at the moment. I did test with two different filter instances (one with 2 and one with 4 parameters), but I should have run the test suite, I guess. Contributing to the core ros packages is new for me.

Does CI test open pull requests?

**Comment by dirk-thomas** [comment]
No, it doesn't at the moment. It only runs on changes on the devel branch (aka after the pull request has been merged).

**Comment by NikolausDemmel** [comment]
Jenkins fails, however I don't see how this is related to this patch...
http://jenkins.ros.org/job/devel-hydro-ros_comm/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/lastBuild/

**Pull request merged**
