### PR TITLE
#1502 revisited: roslaunch: Allow passing _TIMEOUT_SIGINT and _TIMEOUT_SIGTERM as parameters

### PR DESCRIPTION
**Pull request by cwecht**
This replaces #1502. The suggested changes have been added. The argument-parser excepts now floats for '--sigint-timeout' and '--sigterm-timeout' to be consistent with DEFAULT_TIMEOUT_SIGINT and DEFAULT_TIMEOUT_SIGTERM.

### CODE REVIEW

**Comment by cwecht** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
This needs to be rebased to resolve conflicts.

**Comment by dirk-thomas** [comment]
@cwecht Closing due to no response. Please consider to open a new pull request targeting `noetic-devel`.

**Comment by peci1** [comment]
@dirk-thomas Did you look at [my PR](https://github.com/cwecht/ros_comm/pull/2)? I know that @cwecht did not merge it, but I could easily try to retarget it here and not at @cwecht's repo.

**Comment by peci1** [comment]
But I'd still like to target it to melodic.

**Comment by dirk-thomas** [comment]
> Did you look at my PR? I know that @cwecht did not merge it, but I could easily try to retarget it here and not at @cwecht's repo.

No, I haven't. Please feel free to open a new PR targeting `noetic-devel` which contains your proposed changes.

> But I'd still like to target it to melodic.

Any PR should target the default branch which is for the latest distro (now `noetic-devel`). After it has been merged it can / will be considered for backorting.

**Comment by peci1** [comment]
Okay, I'll have a look at it.

**Comment by peci1** [comment]
Continued in #1937.

**Comment by peci1** [comment]
#1937 has been merged into `noetic_devel`. Could it be considered for backporting into melodic?

**Comment by dirk-thomas** [comment]
I will be considered as part of a backport PR before the next Melodic patch release. All commits from `noetic-devel` will be enumerated in a PR (see past PRs with "backport" in the title) and eventually backported in the order they landed.

**Pull request closed without merging**
