### PR TITLE
[Windows] use double quotes for portable roslaunch-check command.

### PR DESCRIPTION
**Pull request by seanyen**
On Windows, the single quotes will be passed the executable and won't be escaped. In this case, it causes that this line always returns None and throws exceptions like below.
https://github.com/ros/ros_comm/blob/902fb00fc7b2e881575a270a99c3a077ba5cdbba/tools/roslaunch/scripts/roslaunch-check#L88

```
Traceback (most recent call last):
  File "C:\opt\ros\melodic\x64\share\roslaunch\scripts\roslaunch-check", line 90, in <module>
    pkg_dir = r.get_path(pkg)
  File "C:\opt\python27amd64\lib\site-packages\rospkg\rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: <exception str() failed>
```

### CODE REVIEW

**Comment by seanyen** [comment]
@dirk-thomas This is ready for review and merge. Thanks!

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Pull request merged**
