### PR TITLE
speedier lookups with rosbag info -y -k

### PR DESCRIPTION
**Pull request by olgalupuleac**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please update the PR to not include any generated files. Also the README in the root of the repo seems to be a bad place for the information. Maybe place it in `tools/rosbag/doc` instead?

**Comment by dirk-thomas** [comment]
While the latest commits pass CI the previous comment still applies: do not include any generated files and move the added README file.

**Comment by cwecht** [comment]
Well, as far as I can see, this is basically a C++-reimplementation of ''rosbag infor -y -k".  I think, this should be done in a similar manner as play or record are implemented.

**Comment by dirk-thomas** [comment]
Closing due to long time of inactivity. Please consider opening a new PR targeting the current default branch if you are still interested in getting this patch merged.

**Pull request closed without merging**
