### PR TITLE
Check xmlrpc response is valid before returning.

### PR DESCRIPTION
**Pull request by mikepurvis**
Proposed resolution to #836.

### CODE REVIEW

**Comment by mikepurvis** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
@dirk-thomas Thoughts on this?

**Comment by dirk-thomas** [comment]
I am sorry for not replying earlier but I have to focus on a different project which doesn't allow for much time for ROS tickets.

In the case that the `XmlRpcClient::execute` returns `true` I don't see how the `response` could be invalid. The only case where this function returns `true` (https://github.com/ros/ros_comm/blob/54398ba8bedf254abead9dfffd5bd8e6bb8d72a1/utilities/xmlrpcpp/src/XmlRpcClient.cpp#L111) implies that the previous internal call to `parseResponse` also returned `true` (https://github.com/ros/ros_comm/blob/54398ba8bedf254abead9dfffd5bd8e6bb8d72a1/utilities/xmlrpcpp/src/XmlRpcClient.cpp#L106). And that function only returns `true` if the `result` (aka `response`) is valid (https://github.com/ros/ros_comm/blob/54398ba8bedf254abead9dfffd5bd8e6bb8d72a1/utilities/xmlrpcpp/src/XmlRpcClient.cpp#L470).

Without having run any code I would expect the added condition to be logically redundant. It looks like that it `b` can't be `true` at the same time as `response.valid()` is `false`.

That being said the current code only ensures that the `response` is valid. But the reason this was failing in the first place is that `payload` is invalid. So at the end of `master::execute` the following check might make sense:

```
if (!payload.isValid()) return false;
```

I am not sure though why that would be the case. (I am also not sure if there a valid cases where payload is intentionally invalid.) Eventually debugging into `XMLRPCManager::validateXmlrpcResponse` (https://github.com/ros/ros_comm/blob/d54e9be3421af71b70fc6b60a3bf916e779b43dc/clients/roscpp/src/libros/xmlrpc_manager.cpp#L235-L241) will shed some light into when that happens.

**Comment by mikepurvis** [comment]
Oh you're right, of course, on `payload` vs. `response`— sorry for the distraction on that score.

If it would be of interest, I can try to instrument our bots to find out more about the circumstances of the TypeInvalid payload. We do a lot of rviz-over-wifi here, so it's possible this is down to dropped TCP sessions or something like that.

**Comment by dirk-thomas** [comment]
That would be great. Any information will help to get this resolved. Thanks.

**Comment by mikepurvis** [comment]
Closing this, will resume discussion in #836.

**Pull request closed without merging**
