### PR TITLE
Rename python message_filters.Cache.getLastestTime to getLatestTime

### PR DESCRIPTION
**Pull request by madebyollin**
Per instructions from dirk-thomas on this issue: https://github.com/ros/ros_comm/issues/1449#issuecomment-403118429

### CODE REVIEW

**Comment by madebyollin** [comment]
@ros-pull-request-builder Please retest this? 🤞

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by madebyollin** [comment]
Reading the test outputs, it's still not clear which test failures (if any) are related to the changes in this PR. Some of them (e.g.  `test_random_play`, `__main__.HzTest.test_hz`) are also failing on unrelated PRs. Others (e.g. `Subscriptions.emptyMsg`) are in the `roscpp` tests, and the code changes in this PR only affect the python interface. None seem to reference code I changed... It's difficult for me to interpret the tests without prior knowledge about the test structure/test behavior on previous builds, though.

If any of the test failures _do_ indicate bugs in this PR, please let me know and I can try to fix them. Otherwise, it should hopefully be straightforward to merge these edits. Thanks!

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Pull request merged**
