### PR TITLE
added command line parameter to print out launch args

### PR DESCRIPTION
**Pull request by dlaz**
One of the proposals from the roslaunch sig

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Please rebase to the tip of the branch so that it can be merged.

**Comment by dlaz** [comment]
Rebased to tip of groovy-devel and changed the copyright year.

**Comment by dirk-thomas** [comment]
Please rebase correctly. Now the pull request contains all the changes from the last release and not only your modifications. The pull request should only contain 54a97007712d2768fb9530940e308533af6c4da9 and a8a145627df352c87b368f8041467742ea569a8f

**Comment by dlaz** [comment]
I would not have updated the pull request with a rebase that I thought was done incorrectly. I don't know why it pulled in all of the intervening commits. Mind giving me a pointer to directions for doing it correctly?

**Comment by dirk-thomas** [comment]
The easiest way to update your branch is to checkout the latest version from the official repository and cherry-picking the two changes you made and (force) pushing this to your local repository. Than this pull request should only show your changes and be "green" so mergable.

If that does not work out I could also fetch a copy of your repo and do the cherry-picking manually - that would just bypass the pull request mechanism.

**Comment by tfoote** [comment]
There's instructions for rebasing another pull request here:
https://github.com/ros/rosdistro/pull/533#issuecomment-14980810

Obviously you'll need to update the urls.

**Comment by dlaz** [comment]
Hmm, so when I rebase based on @tfoote's link (which is pretty much what I did the first time), it forces me to commit all of the changes that were pulled in with the fetch, which I think is why they're showing up in the pull request.

@dirk-thomas , do you want to bypass the pull request, or I could just start with a clean version of the official repo and submit a new pull request.

**Comment by dirk-thomas** [comment]
Ok, I cherry-picked the two commits from your repository. Thanks for contributing the patch.

**Pull request closed without merging**
