### PR TITLE
rospy: use threading module rather than thread

### PR DESCRIPTION
**Pull request by wjwwood**
This is a reopening of #284.

### CODE REVIEW

**Comment by wjwwood** [comment]
I have a theory:

The TCPServer class spawns a thread in which it calls an "inbound_handler" which might be spawning threads as well. This might be the source of the behavior change, i.e. calling `thread.start_new_thread` in a thread may behave differently from `threading.Thread.start`.

**Comment by wjwwood** [comment]
This is the issue, `thread.start_new_thread` is equivalent to `threading.Thread` in daemon mode. This is pretty bad, it basically means that when the script ends these threads go on. There should probably be a new pull request for making rospy threads cleanly shutdown.

**Comment by wjwwood** [comment]
http://stackoverflow.com/questions/4003783/translate-thread-start-new-thread-to-the-new-threading-api

**Comment by wjwwood** [comment]
Ok, there is a new commit, which converts this:

``` python
import thread
...
thread.start_new_thread(func, args=(arg1, arg2))
```

Into:

``` python
import threading
...
t = threading.Thread(target=func, args=(arg1, arg2))
t.setDaemon(True)
t.start()
```

**Comment by wjwwood** [comment]
I am running tests now on my mac and on Linux.

**Comment by wjwwood** [comment]
```
% catkin_test_results build/test_results
Summary: 312 tests, 0 errors, 0 failures
```

**Comment by wjwwood** [comment]
@dirk-thomas @tfoote for review.

**Comment by tfoote** [comment]
+1  I'm amazed how few lines this patch is.

**Comment by dirk-thomas** [comment]
+1 Please squash your commits since the in-between state is pretty broken.

**Comment by wjwwood** [comment]
Squashed.

**Pull request merged**
