### PR TITLE
Fixing dangling if-else statement

### LINKED ISSUE #1305: Dangling if-else triggers compilation error | rosbag_storage
I am currently building ROS Kinetic from source using the install generator
on Gentoo Linux (32 bit) --- actually, all this for the Pepper robot, but that is just FYI.

However, [rosbag_storage](https://github.com/ros/ros_comm/tree/1.12.0) fails to compile due to two dangling if else statements (1.12.0) in 

1st)
https://github.com/ros/ros_comm/blob/1.12.10/tools/rosbag_storage/src/lz4_stream.cpp#L180

2nd)
https://github.com/ros/ros_comm/blob/lunar-devel/tools/rosbag_storage/src/bz2_stream.cpp#L131

GCC is 5.4.0.

### PR DESCRIPTION
**Pull request by warp1337**

### CODE REVIEW

**Comment by mikepurvis** [comment]
This commit will have to be cherry-picked to the `lunar-devel` branch and then can be merged there. It will be considered for backport when we're next preparing a release into Kinetic.

**Comment by warp1337** [comment]
Actually in the lunar-devel branch, due to 

<pre>
CONSOLE_BRIDGE_logError
</pre>

the error is "mitigated". Thus, the fix as proposed only needs to be applied 
to tags and/or branches that still use the  

<pre>
logError("unused data already available")
</pre>

If I am right...

**Comment by dirk-thomas** [comment]
The fix should still be applied to the `lunar-devel` branch since without using curly braces the code is fragile in case the macros changes to be either empty or expands into two statements.

**Comment by warp1337** [comment]
Agree. I never understood why people (prefer to) omit the curly braces...

**Comment by dirk-thomas** [comment]
Can you please rebase the patch in order to make it mergable.

**Comment by warp1337** [comment]
I was out of office last week. Will do within 48 hours.

**Comment by warp1337** [comment]
I just tried to rebase based on lunar devel, lots of conflicts... Wouldn't it be easier to add those four curly braces on the lunar devel branch and create a new pull request?

**Comment by dirk-thomas** [comment]
That would be fine too.

**Comment by dirk-thomas** [comment]
Addressed by #1637.

**Pull request closed without merging**
