### PR TITLE
Fix some errors in some probably not frequented code paths melodic

### PR DESCRIPTION
**Pull request by awesomebytes**
Update to https://github.com/ros/ros_comm/pull/1410

Are you gonna backport to Kinetic also?

### CODE REVIEW

**Comment by dirk-thomas** [comment]
#1410 had some additional changes. Are they not applicable to the Melodic branch? Should they be pull requested against an older branch only? If yes, which one would be newest distro which needs those?

> Are you gonna backport to Kinetic also?

All patches are considered for backporting. Since this fixes obvious bugs it will very likely be backported for the next patch release.

**Comment by awesomebytes** [comment]
That are not applicable as the error was fixed already (variable "uri" not
existing in the scope).

So if the file gets backported as it is (which looks more correct) it
should be all fine.

**Comment by dirk-thomas** [comment]
> So if the file gets backported as it is (which looks more correct) it
should be all fine.

The "file" doesn't get backported only the applied patches get cherry-picked to the older branches.

So if older distros need additional fixes please create a separate PR for that targeting the branch with the most recent distro which needs the fix.

**Comment by awesomebytes** [comment]
Ok, I'll need a bit of time to apply the same change to previous
branches/distros (other than kinetic and melodic).
Can you reopen the previous PR and re-target it for kinetic again maybe?

I'll take a look at other branches/distros soon.

2018-05-31 12:19 GMT+10:00 Dirk Thomas <notifications@github.com>:

**Comment by awesomebytes** [comment]
I opened PR on all in-development distros.

Indigo and Kinetic have the same changes.

Lunar and Melodic have the same changes.

I don't know what's the process to apply the same change to all the branches, sorry if this is not in your expected format.

**Comment by dirk-thomas** [comment]
Thanks for the patch!

**Pull request merged**
