### PR TITLE
fix closing and deregistering connection when connect fails (#128)

### PR DESCRIPTION
**Pull request by dirk-thomas**
addressed #128

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@tfoote @wjwwood Please review.

**Comment by wjwwood** [comment]
I assume this line:

https://github.com/ros/ros_comm/blob/8231b4b1559a10d436424868fe45ca232500a692/clients/rospy/src/rospy/impl/tcpros_base.py#L784

does `self.done = True` at some point?

**Comment by dirk-thomas** [comment]
Yes, the parent class sets the boolean flag (https://github.com/ros/ros_comm/blob/8231b4b1559a10d436424868fe45ca232500a692/clients/rospy/src/rospy/impl/transport.py#L98) and calls the callback which performs the `remove_connection()` which was missing before.

**Comment by wjwwood** [comment]
+1

**Pull request merged**
