### PR TITLE
make MasterProxy thread-safe

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addresses #459.

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
+1

**Comment by dirk-thomas** [comment]
I will merge this since the one test failing is flaky and I don't see a way to get it to have a deterministic result.

**Comment by tfoote** [comment]
This was breaking the following tutorial: 

```
import roslib
roslib.load_manifest('turtle_tf2')
import rospy

import math
import tf2_ros
import geometry_msgs.msg
import turtlesim.srv

if __name__ == '__main__':
    rospy.init_node('tf2_turtle')

    tfBuffer = tf2_ros.Buffer()
    listener = tf2_ros.TransformListener(tfBuffer)

    rospy.wait_for_service('spawn')
    spawner = rospy.ServiceProxy('spawn', turtlesim.srv.Spawn)
    turtle_name = rospy.get_param('turtle', 'turtle2')
```

With this error: 

```
Traceback (most recent call last):
  File "/tmp/gt/src/geometry_tutorials/turtle_tf2/scripts/turtle_tf2_listener.py", line 54, in <module>
    turtle_name = rospy.get_param('turtle', 'turtle2')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 452, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msproxy.py", line 115, in __getitem__
    code, msg, value = self.target.getParam(rospy.names.get_caller_id(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
httplib.CannotSendRequest
[turtle_pointer-6] process has died [pid 17683, exit code 1, cmd /tmp/gt/src/geometry_tutorials/turtle_tf2/scripts/turtle_tf2_listener.py __name:=turtle_pointer __log:=/home/tfoote/.ros/log/bbb596b6-169a-11e4-8d1b-3c970ee1fca6/turtle_pointer-6.log].
log file: /home/tfoote/.ros/log/bbb596b6-169a-11e4-8d1b-3c970ee1fca6/turtle_pointer-6*.log
```

We should consider backporting to hydro.

**Pull request merged**
