### PR TITLE
Error when hostnames do not match on remote launch

### PR DESCRIPTION
**Pull request by Timple**
Solves #72

### CODE REVIEW

**Comment by mikepurvis** [comment]
This looks reasonable to me; can't think of a situation where this would result in a false positive. 👍

**Comment by Timple** [comment]
One thing that popped up in my mind: Would this scenario still work?:

computer1: roscore
computer2: subscribed to computer1-core and roslaunch with remote nodes on computer 3

**Comment by tfoote** [comment]
I think that for #72 localhost has specific meaning that it won't talk externally. Otherwise you may have multihoned computers with different hostname on different interfaces etc and I'm not sure that the generic check is as simple as this proposed change.

**Comment by Timple** [comment]
In that case, would comparing against just 'localhost' help?
Other cases like 127.0.0.1 might be giving identical issues, but checking against localhost only might make sense because this is the default of ROS_MASTER_URI. And therefore the most likely to cause issues with users.

**Comment by Timple** [comment]
A colleague ran into the same issue again and it takes quite some debugging to find that your own ROS_MASTER_URI should not contain localhost (the default).

Is anything wrong with my implementation? Or do you like me to rewrite to throw a warning if localhost is used in combination with remote roslaunch?

**Comment by 130s** [comment]
@ros-pull-request-builder retest this please

**Comment by 130s** [comment]
I don't yet have a deep understanding of the issue #72 (its author was me but I just copied from an older repo back then). Especially these days in a containerized world where each container might be designed as self-contained ROS image, I don't know how this change affects or not. That said in a non-containerized, pure multi-host single ROS Master environment this seems reasonable to me.

**Comment by dirk-thomas** [comment]
Please retarget the latest default branch (currently `melodic-devel`) in order to be considered for review and merge.

**Comment by dirk-thomas** [comment]
@Timple @130s Closing due to no response. Please consider to open a new pull request targeting `noetic-devel`.

**Pull request closed without merging**
