### PR TITLE
[FIX] #558 rostest.rosrun now generates coverage reports

### PR DESCRIPTION
**Pull request by VGonPa**
See #558 for more information.

[Review on Reviewable](https://reviewable.io/reviews/ros/ros_comm/559)

### CODE REVIEW

**Comment by VGonPa** [comment]
I've just noticed that this fix seems to create a side effect. 

When you execute a rostest with a `rostest.rosunit` that is called with `sysargs=--cov` the test report gives you a Failure unless you execute the rostest with `--text` option.
(If the test does not have the `sysargs=--cov` it runs OK.

I am going to put the logs in separate comments so they are easier to read.

**Comment by VGonPa** [comment]
Fails when you call the test **without** `--text`:

``` bash
viki@vROS:[~/devel/mona...trunk/catkin_ws]$ rostest rospy_utils param_utils.test 
... logging to /home/viki/.ros/log/rostest-vROS-30718.log
[ROSUNIT] Outputting test results to /home/viki/devel/rosbuild_ws/build/test_results/rospy_utils/rostest-test_param_utils.xml
testTestParamUtils ... FAILURE!
FAILURE: test [TestParamUtils] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testTestParamUtils][failed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 1

ERROR: The following tests failed to run:
 * testTestParamUtils

rostest log file is in /home/viki/.ros/log/rostest-vROS-30718.log
```

**Comment by VGonPa** [comment]
Succeeds if you call it **with** the `--text` argument:

``` bash
viki@vROS:[~/devel/mona...trunk/catkin_ws]$ rostest rospy_utils param_utils.test --text
... logging to /home/viki/.ros/log/rostest-vROS-30904.log
testTestParamUtils (rostest.runner.RosTest) ... [ROSTEST]setup[/home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/test/param_utils.test] run_id[367e57cc-a320-11e4-84f8-000c29ec1189] starting
started roslaunch server http://vROS:52489/
ros_comm version 1.10.10


SUMMARY
========

PARAMETERS
 * /rosdistro
 * /rosversion

NODES

[ROSTEST]setup[/home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/test/param_utils.test] run_id[367e57cc-a320-11e4-84f8-000c29ec1189] done
[ROSTEST]Running test [TestParamUtils]
auto-starting new master
process[master]: started with pid [30918]
ROS_MASTER_URI=http://vROS:22422/
setting /run_id to 367e57cc-a320-11e4-84f8-000c29ec1189
process[rosout-1]: started with pid [30931]
started core service [/rosout]
[ROSTEST]running test TestParamUtils
process[TestParamUtils-2]: started with pid [30943]
PACKAGE: rospy_utils
[ROSUNIT] Outputting test results to /home/viki/devel/rosbuild_ws/build/test_results/rospy_utils/rosunit-test_param_utils.xml
test_atach_parameters ... ok
test_attach_parameters_fails_if_not_allowed_to_create_new_attrib ... ok
test_attach_parameters_returns_empty_obj_if_emtpy_obj_is_passed ... ok
test_attach_parameters_returns_same_object_if_no_parameters ... ok
test_get_all_user_parameters ... ok
test_get_parameters ... ok
test_get_parameters_raises_ParamNotFoundError_when_not_founds_it ... ok
test_get_parameters_raises_TypeError_when_no_attr_passed ... ok
test_load_params ... ok
Name                      Stmts   Miss  Cover
---------------------------------------------
rospy_utils                  28     28     0%
rospy_utils.coroutines      112    112     0%
rospy_utils.func_utils       31     31     0%
rospy_utils.iter_utils        3      2    33%
rospy_utils.param_utils      51     18    65%
---------------------------------------------
TOTAL                       225    191    15%

/home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/src/rospy_utils/param_utils.py:
Missing lines: 22-49, 58, 75, 92, 100, 117, 148

/home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/src/rospy_utils/coroutines.py:
Missing lines: 20-486

/home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/src/rospy_utils/iter_utils.py:
Missing lines: 21-29

/home/viki/devel/monarch/code/trunk/catkin_ws/devel/lib/python2.7/dist-packages/rospy_utils/__init__.py:
Missing lines: 4-37

/home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/src/rospy_utils/func_utils.py:
Missing lines: 21-128
-------------------------------------------------------------
SUMMARY:
 * RESULT: SUCCESS
 * TESTS: 9
 * ERRORS: 0 []
 * FAILURES: 0 []

[TestParamUtils-2] process has finished cleanly
log file: /home/viki/.ros/log/367e57cc-a320-11e4-84f8-000c29ec1189/TestParamUtils-2*.log
[ROSTEST]test [TestParamUtils] finished
[ROSTEST][ROSTEST] test [TestParamUtils] done
[ROSTEST]tearDown[/home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/test/param_utils.test]
shutting down processing monitor...
[rosout-1] killing on exit
[master] killing on exit
... shutting down processing monitor complete
[ROSTEST]rostest teardown /home/viki/devel/monarch/code/trunk/catkin_ws/src/rospy_utils/test/param_utils.test complete
ok

----------------------------------------------------------------------
Ran 1 test in 12.489s

OK

WARNING: overall test result is not accurate when --text is enabled
rostest log file is in /home/viki/.ros/log/rostest-vROS-30904.log


```

**Comment by VGonPa** [comment]
Hi, has anybody been able to test this issue?

I undertand that `Hydro` is getting a bit outdated, but I've seen that the patch could be also applied to [`Indigo`](https://github.com/ros/ros_comm/blob/indigo-devel/tools/rostest/src/rostest/__init__.py#L142)

**Comment by VGonPa** [comment]
I'm not sure about this, but I think a possible path to explore might be in lines [138](https://github.com/ros/ros_comm/blob/indigo-devel/tools/rostest/src/rostest/__init__.py#L138) and [140](https://github.com/ros/ros_comm/blob/indigo-devel/tools/rostest/src/rostest/__init__.py#L140) of `rostest`. It seems that the test report is being done quite differently depending if `--text` is activated or not.

If `--text` is activated, the test report is done with the regular `unittest.TextRunner` and produces the test results correctly. However, when `--text` is **not** activated the report is carried out with [`rosunit.create_xml_runner`](https://github.com/ros/ros/blob/indigo-devel/tools/rosunit/src/rosunit/core.py#L133) instead of `unittest.TextRuner`. 

Therefore, it seems the problem might be in the `rosunit.create_xml_runner` function. But beyond this point I got a lost.

**Comment by dirk-thomas** [comment]
Thanks for the PR. I didn't have the time to look at it yet. It might be a couple more weeks until I can get  to it.

**Comment by VGonPa** [comment]
Ok, meanwhile I'll keep digging a bit on the issue.

**Comment by VGonPa** [comment]
Hi, Dirk, have you been able to check this PR?

**Comment by dirk-thomas** [comment]
You patch lacks the same change for the invocation of `_start_coverage`. It seems both functions expect a list of packages but `_start_coverage` won't raise an exception but silently does the wrong thing.

Beside that I can't reproduce a different behavior with / without the `--text` option. I tried it with a few rostests from this repo and with this patch (including the same change to `_start_coverage`) both invocations work fine for me..

**Comment by VGonPa** [comment]
You are right. I forgot to add the same patch to `_start_coverage`. 

Later today I will try to reproduce the error I got without the `--text` option in another computer.

**Comment by VGonPa** [comment]
I've tested again in different computers and I get the same error. If I try to get the coverage report without the `--text` option passed to the rostest command the test fails. 

Note that I set the `--cov` option in the `rostest.rosrun` call (see [rospy_utils](https://github.com/UC3MSocialRobots/rospy_utils/blob/master/src/test/test_param_utils.py#L128), for instance) instead of setting them directly by the command line. 

¿Did you manage to get coverage reports both with and without the `--text` mode?

**Comment by VGonPa** [comment]
Summary of my experiments with the patch applied (using [my own test](https://github.com/UC3MSocialRobots/rospy_utils/blob/master/src/test/test_param_utils.py) file):

#### Exp 1:
- **In my code**: `rostest.rosrun(PKG, 'test_param_utils', ParamUtils_TestCase,sysargs=['--cov', '--text'])`
- **Execute**: `rostest rospy_utils param_utils.test` 
- **Result**: _FAILS_. See log.

``` sh
monarch@mpc01:[~/monarch/co.../ocular_project]$ rostest rospy_utils param_utils.test
... logging to /home/monarch/.ros/log/rostest-mpc01-23381.log
[ROSUNIT] Outputting test results to /home/monarch/monarch/code/trunk/catkin_ws/build/test_results/rospy_utils/rostest-test_param_utils.xml
test_atach_parameters (__main__.ParamUtils_TestCase) ... ok
test_attach_parameters_fails_if_not_allowed_to_create_new_attrib (__main__.ParamUtils_TestCase) ... ok
test_attach_parameters_returns_empty_obj_if_emtpy_obj_is_passed (__main__.ParamUtils_TestCase) ... ok
test_attach_parameters_returns_same_object_if_no_parameters (__main__.ParamUtils_TestCase) ... ok
test_get_all_user_parameters (__main__.ParamUtils_TestCase) ... ok
test_get_parameters (__main__.ParamUtils_TestCase) ... ok
test_get_parameters_raises_ParamNotFoundError_when_not_founds_it (__main__.ParamUtils_TestCase) ... ok
test_get_parameters_raises_TypeError_when_no_attr_passed (__main__.ParamUtils_TestCase) ... ok
test_load_params (__main__.ParamUtils_TestCase) ... ok

----------------------------------------------------------------------
Ran 9 tests in 0.068s

OK
testTestParamUtils ... FAILURE!
FAILURE: test [TestParamUtils] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testTestParamUtils][failed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 1

ERROR: The following tests failed to run:
 * testTestParamUtils

rostest log file is in /home/monarch/.ros/log/rostest-mpc01-23381.log
```

---

#### Exp 2:
- **In my code**: `rostest.rosrun(PKG, 'test_param_utils', ParamUtils_TestCase,sysargs=['--cov', '--text'])`
- **Execute**: `rostest rospy_utils param_utils.test --text` 
- **Result**: Test passes. Produces coverage report

---

#### Exp 3:
- **In my code**: `rostest.rosrun(PKG, 'test_param_utils', ParamUtils_TestCase,sysargs=['--cov'])`
- **Execute**: `rostest rospy_utils param_utils.test` 
- **Result**:  Test fails. See log:

``` sh
monarch@mpc01:[~/monarch/co.../ocular_project]$ rostest rospy_utils param_utils.test 
... logging to /home/monarch/.ros/log/rostest-mpc01-9707.log
[ROSUNIT] Outputting test results to /home/monarch/monarch/code/trunk/catkin_ws/build/test_results/rospy_utils/rostest-test_param_utils.xml
testTestParamUtils ... FAILURE!
FAILURE: test [TestParamUtils] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 162, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 420, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testTestParamUtils][failed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 1

ERROR: The following tests failed to run:
 * testTestParamUtils

rostest log file is in /home/monarch/.ros/log/rostest-mpc01-9707.log
```

---

#### Exp 4:
- **In my code**: `rostest.rosrun(PKG, 'test_param_utils', ParamUtils_TestCase,sysargs=['--cov'])`
- **Execute**: `rostest rospy_utils param_utils.test --text` 
- **Result**: Same as experiment 2: test passes and generates coverage report.

---

#### Exp 5:
- **In my code**: `rostest.rosrun(PKG, 'test_param_utils', ParamUtils_TestCase, sysargs=None)`
- **Execute**: `rostest rospy_utils param_utils.test --cov` 
- **Result**: Does not run tests. See log:

``` sh
monarch@mpc01:[~/monarch/co.../ocular_project]$ rostest rospy_utils param_utils.test --cov
Usage: rostest [options] [package] <filename>

rostest: error: no such option: --cov
```

**Comment by VGonPa** [comment]
Hi Dirk, have you been able to replicate this?

**Comment by dirk-thomas** [comment]
I am sorry for the long delay. I have applied your patch to the indigo-devel branch: 91cdf3a0af488fd6b633e5e692be4b7130c057ad

**Pull request closed without merging**
