### PR TITLE
Issue947

### PR DESCRIPTION
**Pull request by dirk-thomas**
Replaces #931.

Fixing the original implementing of the caching: #682

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros/ros_team Please review.

**Comment by tfoote** [comment]
Should the update be triggered on a miss too? Previously it only updated on a miss, now it only updates on a success. Otherwise lgtm.

**Comment by bponsler** [comment]
Thanks -- I just confirmed these changes work for me. Reduced XmlLoader.load time from ~12 seconds to ~0.5 seconds (for my specific launch tree).

Do you have any plans to make these same changes in the _indigo-devel_ branch?

**Comment by dirk-thomas** [comment]
@tfoote Good point. While that case might be rare there is no reason to not persist the data in the case of a miss. I modified the code to persist the data in both cases: 1f09fd15ad250f546548751cf84ee7616db92bf2

@bponsler Thank you for checking. Could I maybe ask you to check again (with the additional modification) just to be sure :wink:) Once the changes are merged and have been released into Kinetic (without regressing) they will be considered for backporting into Jade and Indigo.

**Comment by bponsler** [comment]
@dirk-thomas -- no problem. Just checked your latest changes. Works for me. Thanks!

**Comment by dirk-thomas** [comment]
@bponsler Thanks for making sure!

**Pull request merged**
