### PR TITLE
Enable and fix rosmsg tests

### PR DESCRIPTION
**Pull request by gerkey**
As noted in #709, the test suite for `rosmsg` has long been disabled. This PR enables the test suite and updates the tests to make them pass. In some cases, it could be argued that instead the code should be updated instead of the tests. But I feel that's it's less risky to update the tests to match the long-standing behavior of the code.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The failing test from roswtf (`test_offline`) is a known problem (see #752). But the other failing tests are related to this PR.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by gerkey** [comment]
The test failures were caused by:

```
Unknown message class: geometry_msgs/Polygon
```

I added a `test_depend` on `geometry_msgs` in efff5a4.

**Comment by gerkey** [comment]
Replaced by #764.

**Pull request closed without merging**
