### PR TITLE
Add TCP_INFO availability check

### PR DESCRIPTION
**Pull request by otamachan**
As using `TCP_INFO` is not a portable code (#1207),  check its availability before using.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for the quick fix.

@Yay295 can you please try this patch and comment if it works around the problem you have with WSL.

**Comment by Yay295** [comment]
Unfortunately not. This isn't a Python problem, so `hasattr(socket, 'TCP_INFO') is True`. I might be able to catch it in a try-except though.

**Comment by dirk-thomas** [comment]
@Yay295 Can you please propose a PR with a patch which works for you.

**Comment by dirk-thomas** [comment]
Thank you for the patch. I changed the logic in e5112a77ff76c3c99fda42116b4f124392b9e470 in order to simplify the diff.

**Pull request merged**
