### PR TITLE
[rospy] Logging function for rospy with node/func named msg

### PR DESCRIPTION
**Pull request by wkentaro**
Below line outputs below image:

``` python
#!/usr/bin/env python

import rospy

rospy.init_node('a')

rospy.loginfo_func_named('a')
rospy.logwarn_func_named('a')
rospy.logfatal_func_named('a')
rospy.logerr_func_named('a')

rospy.loginfo_node_named('a')
rospy.logwarn_node_named('a')
rospy.logfatal_node_named('a')
rospy.logerr_node_named('a')

rospy.loginfo_node_func_named('a')
rospy.logwarn_node_func_named('a')
rospy.logfatal_node_func_named('a')
rospy.logerr_node_func_named('a')

rospy.loginfo_func_named('%d', 1)
rospy.logwarn_func_named('%d', 1)
rospy.logfatal_func_named('%d', 1)
rospy.logerr_func_named('%d', 1)

rospy.loginfo_node_named('%d', 1)
rospy.logwarn_node_named('%d', 1)
rospy.logfatal_node_named('%d', 1)
rospy.logerr_node_named('%d', 1)

def main():
    rospy.loginfo_func_named('a')
    rospy.logwarn_func_named('a')
    rospy.loginfo_node_named('a')
    rospy.logwarn_node_named('a')
    rospy.loginfo_node_func_named('a')
    rospy.logwarn_node_func_named('a')
main()

class Test(object):
    def __init__(self):
        rospy.loginfo_func_named('a')
        rospy.logwarn_func_named('a')
        rospy.loginfo_node_named('a')
        rospy.logwarn_node_named('a')
        rospy.loginfo_node_func_named('a')
        rospy.logwarn_node_func_named('a')
Test()
```

screen shot 2016-08-25 at 12 06 56 am

### CODE REVIEW

**Comment by tfoote** [comment]
This looks to be extending the API and most of the functionality is covered in the [Console Ouput Formatting](http://wiki.ros.org/rosconsole#Console_Output_Formatting) options for rosconsole without changing the API.

**Comment by wkentaro** [comment]
Oh, i didn't know about it, and it works for functions, but not seems not for methods in class.
The behavior seems defined here:
https://github.com/ros/ros_comm/blob/kinetic-devel/tools/rosgraph/src/rosgraph/roslogging.py#L174
do you have any idea how to display the class name also?
Currently it only outputs `[__init__]` not `[Test::__init__]`.

**Comment by tfoote** [comment]
The available information comes from the [LogRecord datatype](https://docs.python.org/2/library/logging.html#logging.LogRecord) 

You'd need to add logic using the inspect module to do the class lookup: [python2 example](https://stackoverflow.com/questions/961048/get-class-that-defined-method), [python3 example](http://stackoverflow.com/a/25959545/3903832)

**Comment by dirk-thomas** [comment]
Can this be closed then?

**Comment by wkentaro** [comment]
yes.
Moved to #877

**Pull request closed without merging**
