### PR TITLE
rosnode) rosnode_ping to raise exception when socket.err occurs. Update rostest.

### PR DESCRIPTION
**Pull request by 130s**
<b>How is this change verified</b>:
Passes rostest that runs the modified file and methods.

```
$ rostest rosnode rosnode.test
```

<b>Effect to other modules</b>:
According to the command search (see result below), the modified method seems to be used only within the same file, and a pkg that I maintain.

```
/opt/ros/groovy$ grep -r 'rosnode_ping(' .
./lib/python2.7/dist-packages/rosnode/__init__.py:def rosnode_ping(node_name, max_count=None, verbose=False):
./lib/python2.7/dist-packages/rosnode/__init__.py:        if rosnode_ping(node, max_count=1, verbose=verbose):
./lib/python2.7/dist-packages/rosnode/__init__.py:        rosnode_ping(node_name, verbose=True, max_count=options.ping_count)
Binary file ./lib/python2.7/dist-packages/rqt_moveit/moveit_widget.pyc matches
./lib/python2.7/dist-packages/rqt_moveit/moveit_widget.py:            is_node_running = rosnode_ping(nodename, 1)
```

(As a reference to the used version, `ros-groovy-rosnode` is 1.9.44-0quantal-20130326-0855-+0000)

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The patch does not apply to the tip of the branch anymore. Please update the pull request.

Please do not make any changes which are non-essential to your patch (especially white spaces, but also comment lines in the xml) since it makes it more difficult to read and review.

Do you really want to provide the specific exception string in the rqt plugin? Wouldn't it be sufficient to output a generic error message like "could not ping node"?

**Comment by 130s** [comment]
Thanks for the heads up. I've updated my pull req locally, but unittests fail due to the issue #234. I'm waiting my another [pull req](https://github.com/ros/ros_comm/pull/235) to be merged before I sync my local commit to update this pull req. So please wait.

> Do you really want to provide the specific exception string in the rqt plugin? Wouldn't it be sufficient to output a generic error message like "could not ping node"?

Well, if I only consider my particular usecase (my rqt plugin) yes I agree that I don't need specific exception string, so I might handle `ROSNodeIOException`s with different msg string as the same in my `rqt plugin`. But it's `ros_comm`. And I just converted `print` to raise exception with the same message string where raising exception makes sense to me.

**Comment by dirk-thomas** [comment]
Please rebase and consider my above comments.

**Comment by 130s** [comment]
Closing. For some reason the new commit on my fork doesn't get reflected to this pull req (also my fork got messed). Let me open a new pull req.

**Pull request closed without merging**
