### PR TITLE
Changes between 1.15.11 and 1.15.14 for backporting to Melodic

### PR DESCRIPTION
**Pull request by jacobperron**
The following list of changes has been integrated into ros_comm 1.15.13 (Noetic) since the last Melodic release (1.14.11)

**Backported** (in this PR):

* #2165
  * Bug fix

* #2131
  * Bug fix

* #2177
  * Bug fix

* #2171
  * Bug fix

* #2178
  * Documentation fix

* #1937
  * New feature, requested to backport by community (https://github.com/ros/ros_comm/pull/2179)

* #2209 
  * Bug fix

* #2208 
  * Bug fix
 
**Not backported:**

* #2185
  * Already applied in #2186

* #2169
  * Introduced a regression

* #2187

### CODE REVIEW

**Comment by peci1** [comment]
Could I also ask for inclusion of #2208 and #2209? I know they haven't been released in Noetic yet, but given the frequency of releases for either Melodic or Noetic, I fear not having them in this backport would delay them another half a year for Melodic... Especially #2208 fixes an unpleasant regression crated by the previous release...

**Comment by jacobperron** [comment]
@peci1 I'd rather first release those into Noetic (I can do that now) and let them soak for a few weeks until releasing them into Melodic.

**Comment by jacobperron** [comment]
> Especially #2208 fixes an unpleasant regression crated by the previous release...

Oh my mistake, you're right that it would be good to include this fix.

**Review by mjcarroll — APPROVED** [review]

**Comment by MatthijsBurgh** [comment]
Are we waiting for #2208 to be included or anything else that is holding this one?

**Comment by MatthijsBurgh** [comment]
@jacobperron @mjcarroll small friendly ping ;)

**Comment by jacobperron** [comment]
Thanks for the ping. Yes, I was waiting to include #2208. I've updated this this PR to include both #2208 and #2209.

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
Thanks for iterating @jacobperron , looks good to me.

**Comment by peci1** [comment]
Is it possible this PR missed the recent Melodic sync? I somehow thought ros_comm backports and syncs would be synchronized...

**Comment by MatthijsBurgh** [comment]
Yes, it missed the sync. See https://github.com/ros/rosdistro/pull/31924

**Comment by jacobperron** [comment]
Correct, it did not go into the sync. We didn't "synchronize", but I think that's alright since it'll give the changes in ros_comm some time to soak in the testing repo.

**Pull request merged**
