### PR TITLE
check for XXH_malloc NULL return

### LINKED ISSUE #1753: unimplemented null return - malloc may return NULL
XXH_malloc, wrapper of malloc may return NULL,  state need to be checked
https://github.com/ros/ros_comm/blob/29053c4832229efa7160fb944c05e3bc82e11540/utilities/roslz4/src/xxhash.c#L333-L334

### PR DESCRIPTION
**Pull request by artivis**
Edit: I must be tired as I missed #1765... This PR is therefore nearly a duplicate, only diff is [here](https://github.com/ros/ros_comm/pull/1778/files#diff-908b2ea7de4ac66e6e36b226b0199d3cR262).

fix #1753

### CODE REVIEW

**Comment by artivis** [comment]
@danielwangksu FYI

**Comment by danielwangksu** [comment]
> @danielwangksu FYI

Cool! Looks like found the same thing. i will close mine

**Comment by artivis** [comment]
> Cool! Looks like found the same thing. i will close mine

Sorry I didn't mean for you to close your PR ^^.

**Comment by cwecht** [comment]
LGTM

**Comment by dirk-thomas** [comment]
Thank you for the fix.

**Pull request merged**
