### PR TITLE
[rostopic] Get parent topics (upstream in pipeline) with rostopic hz

### PR DESCRIPTION
**Pull request by wkentaro**
Moved from https://github.com/ros/ros_comm/pull/718
to send PR to K

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Should there be a non-recursive option?

I think the documentation needs to be rephrased. I know what you mean with "the node of specified topic" but that is not very clear. Also the term `parent` is not that good imo. @ros/ros_team What do you think? Any better naming suggestions.

**Comment by wjwwood** [comment]
If this is recursive, does it avoid cycles?

I don't have any suggestions for naming. Maybe upstream rather than parent, but upstream implies a tree to me, which again is not necessarily the case.

**Comment by dirk-thomas** [comment]
`upstream` sounds like a better term to me too.

> Get topics to which the node of specified topic subscribes to.

This doc string could be more precise imo, e.g.: "Get topics to which all nodes publishing the passed topic are subscribed to."

When thinking about this more the logic to consider upstream topics (recursively or non-recursively) could be useful beyond `rostopic hz`. Maybe it would be better to have a separate verb (or an existing one with special arguments) which returns that upstream topic list. And then the result of that can be passed to `rostopic hz`?

Anyway before integrating this feature a bug with multiple topics and `rostopic hz` needs to be addressed: https://github.com/ros/ros_comm/pull/712#issuecomment-244490918

**Comment by wkentaro** [comment]
> upstream sounds like a better term to me too.
> 
> Get topics to which the node of specified topic subscribes to.
> This doc string could be more precise imo, e.g.: "Get topics to which all nodes publishing the passed topic are subscribed to."

I agree.

> When thinking about this more the logic to consider upstream topics (recursively or non-recursively) could be useful beyond rostopic hz. Maybe it would be better to have a separate verb (or an existing one with special arguments) which returns that upstream topic list. And then the result of that can be passed to rostopic hz?

+1
Maybe `rostopic upstream /topic`?

**Comment by dirk-thomas** [comment]
The proposed verb name `upstream` sounds ok to me. @ros/ros_team Any thoughts on this?

**Comment by wjwwood** [comment]
Fine by me.

**Comment by dirk-thomas** [comment]
Closing due to long time of inactivity. Please consider opening a new PR targeting the current default branch if you are still interested in getting this patch merged.

**Pull request closed without merging**
