### PR TITLE
debug failing RosAssert tests on Debian Stretch

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The same [hash](https://github.com/ros/ros_comm/commit/94aaaec56e51840d8a39de383c6e89054af97e1e) which passed before on [melodic/stretch](http://build.ros.org/view/Mdev_ds/job/Mdev_ds__ros_comm__debian_stretch_amd64/5/) fails the `RosAssert` tests in [recent builds](http://build.ros.org/view/Mdev_ds/job/Mdev_ds__ros_comm__debian_stretch_amd64/7/) as well as this [PR CI](http://build.ros.org/job/Mpr_ds__ros_comm__debian_stretch_amd64/40/).

**Comment by dirk-thomas** [comment]
Testing in a local Debian Stretch docker container passed the tests :unamused:

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
This is just mindless brainstorming, but some observations:

- They're all [death tests](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#death-tests), which fork and then from the child assert a particular termination condition for the parent.
- In all cases, there's an expected textual output which isn't being seen.

Given how operating system-y this stuff is, I have to ask what kernel you're running locally vs. what's on the buildfarm workers?

Also, if this is a race issue (possibly exacerbated by difference compiler optimization defaults?) might hypervisor load have something to do with it? I don't know how to shake out this hypothesis, but it's bizarre how consistent it is on the CI machine.

**Comment by mikepurvis** [comment]
Not as consistent as I thought though. Of the recent non-PR builds which have been kicked off as a consequence of me merging stuff, visible at http://build.ros.org/job/Mdev_ds__ros_comm__debian_stretch_amd64/:

- 13, 14, 15, and 16 have the RosAssert failures.
- 17 has no test failures, but includes the GCC warning committed by mistake in #1206.
- 18 has the spurious RandomPlay failure.

**Comment by dirk-thomas** [comment]
> I have to ask what kernel you're running locally vs. what's on the buildfarm workers?

I am running 16.04 locally (currently 4.4.0-119). The buildfarm is using a standard Ubuntu / Debian docker image on top of a Ubuntu 16.04 host (so also a 4.4.0 kernel).

**Comment by dirk-thomas** [comment]
Closing since not being investigated.

**Pull request closed without merging**
