### PR TITLE
Rostest target with args

### PR DESCRIPTION
**Pull request by dirk-thomas**
Replaces #456.

@ct2034 FYI

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by wjwwood** [comment]
+1 for Indigo and for backports to Hydro

**Comment by dirk-thomas** [comment]
I updated the patch to actually only consider the passed `ARGS` rather then `ARGN`. It now also passes the correct xunit file. See ff1de571b61d0e0653e5297f49158789fa5b87f1.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by dirk-thomas** [comment]
@ct2034 Please try the latest version of the patch and verify that it works for you as expected.

**Comment by ct2034** [comment]
@dirk-thomas I tried it with a test project. It is working as expected. :+1: :)
But is it possible to include these changes also to hydro? Because the main project I need this for is still running hydro.

**Comment by dirk-thomas** [comment]
Cherry-picked in 8761d8141b1abebe1b5fac9941390ec8b9160f4c. Will be available as 1.10.11 soonish.

**Pull request merged**
