### PR TITLE
Actually send the length byte in python 3

### PR DESCRIPTION
**Pull request by eric-wieser**
Fixes regresssion of #717

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Thank you for the patch. The first commit is a crucial fix (0752719283c6f2d8b33d2d7c7eaf7b4e6b69499f). Since the remaining three commits only refactor the code I squashed them into one (7a3d14d89d89a528ff39816a11d477433d59282d).

**Comment by eric-wieser** [comment]
I'm slightly worried by how this failed the CI...

**Comment by dirk-thomas** [comment]
I am not :wink: The Jade job passed and the Indigo job just had a single failing test which is sadly flaky.

**Comment by eric-wieser** [comment]
I'm guessing there are no python 3 tests on travis right now. Does ROS even official support Python 3 before ROS 2.0?

**Comment by dirk-thomas** [comment]
We try to support users which build ROS 1 from source. Commonly it is only the case on other platforms like Gentoo that they want to use Python 3. I don't expect that any ROS 1 distribution in the near future will switch to Python 3 simply because the community does not want to deal with the effort necessary to update existing code.

Btw. the pull request testing doesn't use Travis at all but the ROS Jenkins server from build.ros.org. And yes, it only tests with Python 2.

**Comment by dirk-thomas** [comment]
FYI this patch needed fixing as proposed in #759.

**Comment by eric-wieser** [comment]
Did you mean to link to the same page you posted on?

**Comment by dirk-thomas** [comment]
Of course - not :wink: #789

**Pull request closed without merging**
