### PR TITLE
Specialize BagCallbackT for MessageInstance

### PR DESCRIPTION
**Pull request by efernandez**
Specialize `BagCallbackT` for `MessageInstance` so the overloaded `call` method calls the callback directly with the `MessageInstance` object.

This way the client callback can access the connection information, which is useful when processing a bag file to create a new one b/c then we can keep the message time and connection information, e.g. the _latch_ property.

### CODE REVIEW

**Comment by efernandez** [comment]
FYI @dirk-thomas

**Comment by mikepurvis** [comment]
Looks reasonable— related to #1372 in terms of overall objective, though that one is for the filter command whereas this is the C++ bag API.

:+1:

**Comment by mikepurvis** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
Since this is a header-only change, a CI pass isn't super meaningful. It's certainly not a complicated implementation, but I wonder if there might be some kind of trivial test which could be added to [test_rosbag_storage](https://github.com/ros/ros_comm/tree/melodic-devel/test/test_rosbag_storage)?

**Comment by efernandez** [comment]
@mikepurvis I agree, I'd add a test to `test_rosbag_storage`.
Do you know where the bag files used in those tests are?
For example, I see `/tmp/swap1.bag`, but I can't see where it's on the repo or any cmake rule to download it.

**Comment by mikepurvis** [comment]
@efernandez It gets written as part of the test: https://github.com/ros/ros_comm/blob/e96c407c64e1c17b0dd2bb85b67f388380527097/test/test_rosbag_storage/src/swap_bags.cpp#L9-L12

**Comment by efernandez** [comment]
Thanks.

I've just added a unit test (creating a simple test bag on runtime as the other tests in this package do).

**Comment by mikepurvis** [comment]
@ros-pull-request-builder retest this please

**Comment by mikepurvis** [comment]
Remaining failures are known-flaky. Thanks for this contribution!

**Pull request merged**
