### PR TITLE
Fix negative numbers in ros statistics

### LINKED ISSUE #1509: traffic is negative when using ros statistics, if a new connection is created between the same nodes
1. the `last_bytes_sent` is stored and will be used when the same `callid` is encountered

Solution:
1. Check out `connection`, a fresh new `bytes_sent` should be used if a new connection is created

### PR DESCRIPTION
**Pull request by foodtooth**
Fix ros/ros_comm#1509

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by foodtooth** [comment]
have no idea why ci test failed

**Comment by dirk-thomas** [comment]
> have no idea why ci test failed

The failing tests were unrelated to this patch and should be fixed in the next CI build.

@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
The current patch [breaks ABI](http://www.ros.org/reps/rep-0009.html#what-s-not-allowed) so it shouldn't be merged into Melodic as is but only into future distros. The alternative would be to add a new function with the new argument (in addition to the existing one) to avoid breaking ABI. Then it could be considered for Melodic (and potential backports).

**Comment by foodtooth** [comment]
> The current patch [breaks ABI](http://www.ros.org/reps/rep-0009.html#what-s-not-allowed) so it shouldn't be merged into Melodic as is but only into future distros. The alternative would be to add a new function with the new argument (in addition to the existing one) to avoid breaking ABI. Then it could be considered for Melodic (and potential backports).

Hi, thanks for the link, great content to check out. As to the comments about adding new function, does it mean that I need to overload the existing function, which seems like still forbidden according to the link.

**Comment by dirk-thomas** [comment]
> As to the comments about adding new function, does it mean that I need to overload the existing function, which seems like still forbidden according to the link.

You are right. I missed that adding an overload if there is one yet isn't allowed either.

The only option for staying ABI compatible would be to introduce a new function, e.g. `callback_with_connection_id(...)`. and call that one instead.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Pull request merged**
