### PR TITLE
Small fixes for Python 3 compatibility.

### PR DESCRIPTION
**Pull request by aballier**
Here is a set of small independent patches to improve python 3 compatibility. These can be squashed if desired.

I have a few more pending but their correctness is more debatable.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder

**Comment by gaboose** [comment]
+1

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
Please resolve the merge conflicts to allow Jenkins to test the patch.

**Comment by dirk-thomas** [comment]
@mikepurvis might look into resolving conflicts on this one and targeting kinetic-devel.

**Pull request closed without merging**
