### PR TITLE
[topic_tools] relay_field which allows relay topic fields to another fields

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
The output is like this::

relay_field

Basic usage is::

```
$ rosrun rospy_tutorials talker.py

$ rosrun topic_tools relay_field /chatter /image sensor_msgs/Image "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: m.data
height: 0
width: 0
encoding: ''
is_bigendian: 0
step: 0
data: ''"

$ rostopic echo /image
header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: hello world 1436995720.88
height: 0
width: 0
encoding: ''
is_bigendian: 0
step: 0
data: ''
...
```

**Comment by wkentaro** [comment]
relates to https://github.com/ros/ros_comm/issues/638

**Comment by wjwwood** [comment]
Ok, thanks we'll get to this as soon as we can!

**Comment by dirk-thomas** [comment]
Thanks for creating this new script. Currently it is not yet being installed and therefore would not be part of the Debian package. Please add it to the list of installed scripts: https://github.com/ros/ros_comm/blob/61d987de96b672291dc76592d3c5be28ce72ff5a/tools/topic_tools/CMakeLists.txt#L66-L72

**Comment by wkentaro** [comment]
Thanks. I added it to the list.

**Comment by dirk-thomas** [comment]
Thanks. I have squashed the commits and fixed a few minor Python style issues. It has been merged in 2faea451097966190c4d6e5a989f0228e53c8bc8.

**Comment by wkentaro** [comment]
Thanks.

2015年9月17日木曜日、Dirk Thomasnotifications@github.comさんは書きました:

> Thanks. I have squashed the commits and fixed a few minor Python style
> issues. It has been merged in 2faea45
> https://github.com/ros/ros_comm/commit/2faea451097966190c4d6e5a989f0228e53c8bc8
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros/ros_comm/pull/639#issuecomment-140907830.

## 

和田 健太郎 / Kentaro Wada
http://wkentaro.com http://www.wkentaro.com

**Comment by gavanderhoorn** [comment]
Has this ever been documented? The `topic_tools` [wiki page](http://wiki.ros.org/topic_tools) does not list it.

**Comment by 130s** [comment]
> Has this ever been documented? The `topic_tools` [wiki page](http://wiki.ros.org/topic_tools) does not list it.

Might not be super helpful but I added this feature to the list with the smallest description and a link to this PR [from the wiki](http://wiki.ros.org/action/info/topic_tools?action=diff&rev2=46&rev1=45).

**Comment by abaldur** [comment]
Is it possible to use the relay_field with arrays?
Let's say I have a topic `/array_of_floats` with msg type: `float64[] data`.
The following does not work for me:
`rosrun topic_tools relay_field /array_of_floats /value_of_first_index std_msgs/Float64 "{data: m.data[0]}"`
Any ideas?

**Comment by cwecht** [comment]
`rostopic pub /array_of_floats std_msgs/Float64MultiArray "{data: [3.4, 3] }" -r 1.0`
`rosrun topic_tools relay_field /array_of_floats /value_of_first_index std_msgs/Float64 "data: m.data[0]"
`

This works. It seems, that the expression you have passed is not a Python expression.

**Comment by abaldur** [comment]
Got it, thx @cwecht

**Comment by marcelino-pensa** [comment]
In case anyone is a noob like I am and is wondering how to run the example above through a launch file, this is how you do it:
```
<launch>
  <node pkg="topic_tools" type="relay_field"
        name="field_relayer"
        args="/chatter /image sensor_msgs/Image 
            '{header:
                {seq: 0,
                stamp: {secs: 0, nsecs: 0},
                frame_id: m.data},
            height: 0,
            width: 0,
            encoding: '',
            is_bigendian: 0,
            step: 0,
            data: ''}' "/>
</launch>
```

**Comment by BereNiM** [comment]
Hello, I'm newie in ROS. I have a topic with some fields (see the image) and I want to send the information from proces_value to another node (/states). I've tried something like `rosrun topic_tools relay_field /lidar/joint1_position_controller/state/process_value /state std_msgs/Float64 "{data: m.data}"` but it doesn't work :( Is it possible to do that with relay_field tool?

image

Thanks in advance (:

**Comment by marcelino-pensa** [comment]
It seems like this package is completely broken in `Noetic`, as not even the simple example of the OP works (issue as described in #2167 )
=/

**Pull request closed without merging**
