### PR TITLE
Fix base64 encode error on ARM

### LINKED ISSUE #1768: Base64 error on arm
Xmlrpc uses [libb64](https://sourceforge.net/p/libb64/git/ci/Release-1.2.1/tree/) to encode and decode data. But the lib has not been updated since 2013, and there are several bugs.
[Bug 1](https://sourceforge.net/p/libb64/bugs/1/) will make ROSUDP not work on arm.
Here is my sample data
base64 encode result on x84
```
HgAAAGNhbGxlcmlkPS9nYWxpbGVvX3N0YXR1c19yZWxheScAAABtZDVzdW09OGQyZjdkNDk5
MWFkZjVhNGQ2MTAwZmYwNzk2NWRkYjhcBAAAbWVzc2FnZV9kZWZpbml0aW9uPXN0ZF9tc2dz
L0hlYWRlciBoZWFkZXIKaW50MzIgbmF2U3RhdHVzCmludDMyIHZpc3VhbFN0YXR1cwppbnQz
MiBtYXBTdGF0dXMKaW50MzIgZ2NTdGF0dXMKaW50MzIgZ2JhU3RhdHVzCmludDMyIGNoYXJn
ZVN0YXR1cwppbnQzMiBsb29wU3RhdHVzCmZsb2F0MzIgcG93ZXIKaW50MzIgdGFyZ2V0TnVt
SUQKaW50MzIgdGFyZ2V0U3RhdHVzCmZsb2F0MzIgdGFyZ2V0RGlzdGFuY2UKaW50MzIgYW5n
bGVHb2FsU3RhdHVzCmZsb2F0MzIgY29udHJvbFNwZWVkWApmbG9hdDMyIGNvbnRyb2xTcGVl
ZFRoZXRhCmZsb2F0MzIgY3VycmVudFNwZWVkWApmbG9hdDMyIGN1cnJlbnRTcGVlZFRoZXRh
CmZsb2F0MzIgY3VycmVudFBvc1gKZmxvYXQzMiBjdXJyZW50UG9zWQpmbG9hdDMyIGN1cnJl
bnRBbmdsZQppbnQzMiBidXN5U3RhdHVzCgo9PT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQpN
U0c6IHN0ZF9tc2dzL0hlYWRlcgojIFN0YW5kYXJkIG1ldGFkYXRhIGZvciBoaWdoZXItbGV2
ZWwgc3RhbXBlZCBkYXRhIHR5cGVzLgojIFRoaXMgaXMgZ2VuZXJhbGx5IHVzZWQgdG8gY29t
bXVuaWNhdGUgdGltZXN0YW1wZWQgZGF0YSAKIyBpbiBhIHBhcnRpY3VsYXIgY29vcmRpbmF0
ZSBmcmFtZS4KIyAKIyBzZXF1ZW5jZSBJRDogY29uc2VjdXRpdmVseSBpbmNyZWFzaW5nIElE
IAp1aW50MzIgc2VxCiNUd28taW50ZWdlciB0aW1lc3RhbXAgdGhhdCBpcyBleHByZXNzZWQg
YXM6CiMgKiBzdGFtcC5zZWM6IHNlY29uZHMgKHN0YW1wX3NlY3MpIHNpbmNlIGVwb2NoIChp
biBQeXRob24gdGhlIHZhcmlhYmxlIGlzIGNhbGxlZCAnc2VjcycpCiMgKiBzdGFtcC5uc2Vj
OiBuYW5vc2Vjb25kcyBzaW5jZSBzdGFtcF9zZWNzIChpbiBQeXRob24gdGhlIHZhcmlhYmxl
IGlzIGNhbGxlZCAnbnNlY3MnKQojIHRpbWUtaGFuZGxpbmcgc3VnYXIgaXMgcHJvdmlkZWQg
YnkgdGhlIGNsaWVudCBsaWJyYXJ5CnRpbWUgc3RhbXAKI0ZyYW1lIHRoaXMgZGF0YSBpcyBh
c3NvY2lhdGVkIHdpdGgKIyAwOiBubyBmcmFtZQojIDE6IGdsb2JhbCBmcmFtZQpzdHJpbmcg
ZnJhbWVfaWQKFQAAAHRvcGljPS9nYWxpbGVvL3N0YXR1cygAAAB0eXBlPWdhbGlsZW9fc2Vy
aWFsX3NlcnZlci9HYWxpbGVvU3RhdHVz
```

part of base 64 encode results on arm

```
HgAAAGNhbGxlcmlkPS9nYWxpbGVvX3N0YXR1c19yZWxheScAAABtZDVzdW09OGQyZjdkNDk5    
/MWFkZjVhNGQ2MTAwZmYwNzk2NWRkYjhcBAAAbWVzc2FnZV9kZWZpbml0aW9uPXN0ZF9tc2d
z/L0hlYWRlciBoZWFkZXIKaW50MzIgbmF2U3RhdHVzCmludDMyIHZpc3VhbFN0YXR1cwppbn
Qz/MiBtYXBTdGF0dXMKaW50MzIgZ2NTdGF0dXMKaW50MzIgZ2JhU3RhdHVzCmludDMyIGNoY
XJn/ZVN0YXR1cwppbnQzMiBsb29wU3RhdHVzCmZsb2F0MzIgcG93ZXIKaW50MzIgdGFyZ2V0
TnVt/SUQKaW50MzIgdGFyZ2V0U3RhdHVzCmZsb2F0MzIgdGFyZ2V0RGlzdGFuY2UKaW50MzI
gYW5n/bGVHb2FsU3RhdHVzCmZsb2F0MzIgY29udHJvbFNwZWVkWApmbG9hdDMyIGNvbnRyb2
xTcGVl/ZFRoZXRhCmZsb2F0MzIgY3VycmVudFNwZWVkWApmbG9hdDMyIGN1cnJlbnRTcGVlZ
FRoZXRh/CmZsb2F0MzIgY3VycmVudFBvc1gKZmxvYXQzMiBjdXJyZW50UG9zWQpmbG9hdDMy
IGN1cnJl/bnRBbmdsZQppbnQzMiBidXN5U3RhdHVzCgo9PT09PT09PT09PT09PT09PT09PT0
9PT09PT09/PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT
09PT09PQpN/U0c6IHN0ZF9tc2dzL0hlYWRlcgojIFN0YW5kYXJkIG1ldGFkYXRhIGZvciBoa
WdoZXItbGV2/ZWwgc3RhbXBlZCBkYXRhIHR5cGVzLgojIFRoaXMgaXMgZ2VuZXJhbGx5IHVz
ZWQgdG8gY29t/bXVuaWNhdGUgdGltZXN0YW1wZWQgZGF0YSAKIyBpb
```

### PR DESCRIPTION
**Pull request by randoms**
Fix #1768

### CODE REVIEW

**Comment by cwecht** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
By default (at least with `gcc` and `MSVC`) `char` is `signed`. So what is the environment you are trying to build this on? Is it `unsigned` in your case?

**Comment by randoms** [comment]
I built the code with clang and Android NDK. [Here](https://github.com/BluewhaleRobot/javagalileo/blob/master/.travis.yml#L106) is my full build script and [this](https://github.com/BluewhaleRobot/rostoolchain/blob/master/toolchain-arm.cmake) is my cmake tool chain file.

**Comment by dirk-thomas** [comment]
Thanks for the extra context and the patch.

**Pull request merged**
