### PR TITLE
fix rosbag record --node (fix #357)

### LINKED ISSUE #357: `rosbag record --node` crashes if monitored node dies violently
To reproduce, compile the following two programs:

```
// talker.cpp
#include "ros/ros.h"
#include "std_msgs/Int32.h"

#include <sstream>

int main(int argc, char **argv)
{
  ros::init(argc, argv, "talker");
  ros::NodeHandle n;
  ros::Publisher chatter_pub = n.advertise<std_msgs::Int32>("chatter", 1000);
  ros::Rate loop_rate(10);

  int count = 0;
  while (ros::ok())
  {
    std_msgs::Int32 msg;
    msg.data = count;
    chatter_pub.publish(msg);
    ros::spinOnce();
    loop_rate.sleep();
    ++count;
  }

  return 0;
}
```

```
// listener.cpp
#include "ros/ros.h"
#include "std_msgs/Int32.h"

void chatterCallback(const std_msgs::Int32::ConstPtr& msg)
{
    ROS_INFO("I heard: [%d]", msg->data);
    if (msg->data == 30) {
        _exit(-1);
    }
}

int main(int argc, char **argv)
{
  ros::init(argc, argv, "listener");
  ros::NodeHandle n;
  ros::Subscriber sub = n.subscribe("chatter", 1000, chatterCallback);
  ros::spin();
  return 0;
}
```

Now, in four separate terminals:

```
$ roscore
```

```
$ rosbag record --node /listener -O test.bag
```

```
$ ./listener
```

```
$ ./talker
```

The rosbag process will exit with the exception "terminate called after throwing an instance of 'XmlRpc::XmlRpcException'" and leave a broken bag 'test.bag.active' that cannot be fixed by `rosbag reindex`.

The problem can be traced to the Recorder::doCheckMaster() function in ros_comm/tools/rosbag/src/recorder.cpp.

Changing line 570 fixes it:

```
- if (!c.isFault() && resp.size() > 0 && static_cast<int>(resp[0]) == 1)
+ if (!c.isFault() && resp.valid() && resp.size() > 0 && static_cast<int>(resp[0]) == 1)
```

Note also that there is an error in line 578:

```
ROS_ERROR("Node at: [%s] failed to return subscriptions.", static_cast<std::string>(resp[2]).c_str());
```

Here, `resp` is meant to refer to the response to the XmlRpc "lookupNode" call to master, but it actually refers to the "getSubscriptions" call. Thus, the error messsage does not print a URI, as intended.

### PR DESCRIPTION
**Pull request by dirk-thomas**
@tfoote @wjwwood Please review.

### CODE REVIEW

**Comment by wjwwood** [comment]
Does this address the comment about line 578?

**Comment by dirk-thomas** [comment]
Yes, the inner variables got a different name so that the error message actually shows the information from the outside response.

**Comment by wjwwood** [comment]
+1

**Comment by tfoote** [comment]
+1

**Pull request merged**
