### PR TITLE
[rosout] Proper logrotation for rosout

### LINKED ISSUE #854: rosout log rotation is odd
Normally you'd expect that the rosout log file is rotated as usual (https://en.wikipedia.org/wiki/Log_rotation) by increasing the number in the suffix for old log file such that it is always guaranteed that rosout.log.2 is older than rosout.log.1. The current implementation moves rosout.log to rosout.log.(current_back_index % 10) during "rotation", thus the ordering is not preserved as you would expect it.

### PR DESCRIPTION
**Pull request by mgrrx**
This PR fixes #854 by rotating the log files as usual in Linux to guarantee the ordering of log files (https://en.wikipedia.org/wiki/Log_rotation).
As discussed previously, this PR does not touch the initializers of the class and targets the Luna release.

### CODE REVIEW

**Comment by mikepurvis** [comment]
Summoning @gregwjacobs who is likely to have an opinion on this.

It'd be great to have some tests covering this behaviour but otherwise LGTM.

**Comment by mgrrx** [comment]
I also thought about writing a test for this functionality but with the current implementation we always need to write at least 100MB to the disk to see that the log rotates once - which I think is too much for a test. I'd therefor expose the max file size parameter as a ros parameter or command line argument and write the test with a reduced file size.
Do you prefer to have the test together with this PR or should I create a new ticket and PR the test?

**Comment by dirk-thomas** [comment]
I have cherry-picked your patch to the newly created lunar-devel branch: ce4d7263138719590ca826fce02cae9f5bc3904a

In that process I have removed the unrelated whitespace change (https://github.com/ros/ros_comm/pull/991/files#diff-c21b75d2d000be7cceac00629a0a9e23R94) as well as readded the output to `cout` informing the user that the log is being rotated (https://github.com/ros/ros_comm/commit/ce4d7263138719590ca826fce02cae9f5bc3904a#diff-c21b75d2d000be7cceac00629a0a9e23R181).

Thank you!

**Comment by dirk-thomas** [comment]
It would be great if you could create a separate PR for making the limit configurable as well as cover the feature with tests.

**Pull request closed without merging**
