### PR TITLE
[backport kinetic] rosconsole: don't use 0 as null pointer in macros

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Essentially https://github.com/ros/rosconsole/pull/14.

PR as suggested in https://github.com/ros/rosconsole/pull/14#issuecomment-500095989.

### CODE REVIEW

**Comment by cwecht** [comment]
why not nullptr? This will actually silence compiler warnings.

**Comment by gavanderhoorn** [comment]
This is a straight copy of https://github.com/ros/rosconsole/pull/14.

`NULL` is used as it will resolve to `nullptr` on platforms that support it. For other platforms it'll still be `0`.

According to the author of https://github.com/ros/rosconsole/pull/14.

**Comment by cwecht** [comment]
Well, ok. Let's merge this!

**Comment by dirk-thomas** [comment]
I changed the target branch to `melodic-devel`. Please update the patch to cleanly apply.

**Comment by gavanderhoorn** [comment]
@dirk-thomas: I'm not sure I understand: I thought that `ros/rosconsole` serviced Melodic, and this repository was for Kinetic and older (at least for the logging infra).

That's why I asked about Kinetic and `ros_comm` in https://github.com/ros/rosconsole/pull/14#issuecomment-498611264.

**Comment by gavanderhoorn** [comment]
@dirk-thomas: :bellhop_bell: ?

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
Thanks for the patch.

(The Melodic CI results aren't valid anymore.)

**Comment by gavanderhoorn** [comment]
Thanks @dirk-thomas :+1: 

apologies for the confusion.

**Pull request merged**
