### PR TITLE
Should fix #1338 for kinetic

### LINKED ISSUE #1338: rospy.wait_for_message breaks for depth image: Timeout error
Hi,

I am always getting timeout errors related to the depth image which is published by gazebo. I tried to increase the timeout value, but it didn't helped. 

Is there any advice on this issue?

```
        while image_data is None:
            try:
                image_data = rospy.wait_for_message('/camera/depth/image_raw', Image)
            except CvBridgeError as e:
                print(e)
```

The error is as follows: 
```
File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 417, in wait_for_message
raise rospy.exceptions.ROSException("timeout exceeded while waiting for message on topic %s"%topic)
rospy.exceptions.ROSException: timeout exceeded while waiting for message on topic /camera/depth/image_raw
```

Thanks!

### PR DESCRIPTION
**Pull request by lucbettaieb**
https://github.com/ros/ros_comm/issues/1383

### CODE REVIEW

**Comment by lucbettaieb** [comment]
@mikepurvis FYI

**Comment by lucbettaieb** [comment]
Oops I messed up the commit issue number.  If this looks good I'll rebase and fix it.

**Comment by cwecht** [comment]
This duplicates  #1685.

**Comment by lucbettaieb** [comment]
@cwecht Thanks, didn't see that.  I'll close this.

**Pull request closed without merging**
