### PR TITLE
Add a new option to publish when a bag write begin

### PR DESCRIPTION
**Pull request by AnthonyBirot**
I use the split mode of the bag recorder to save multiples hours bags. And I need to know when the rosbag record node begin to write a new bag, because I want to publish some topics just at the begin.

I don't wan't to publish in continuous topics to be sure it is in bags.
I did the PR in the kinetic branch because in my project i use it and i can't change.

This pull request is linked to the #1522 pull request. This is the same changes but done on melodic instead of kinetic.

### CODE REVIEW

**Comment by AnthonyBirot** [comment]
I try to know why the unit tests don't work but I don't understand why my changes make mistakes in test_rospy. And when i run the same test on my computer, it works.
Can you help me to know why my changes make crash this unit test ?

**Comment by dirk-thomas** [comment]
The test might just be flaky.

@ros-pull-request-builder retest this please

**Comment by AnthonyBirot** [comment]
Thanks it works !

**Comment by dirk-thomas** [comment]
Thanks for the contribution.

Please consider adding the new option to the documentation in the wiki (marking it as "new in Melodic"). Please post the link to the edit here for future reference.

**Comment by AnthonyBirot** [comment]
http://wiki.ros.org/rosbag/Commandline

See publish option

**Comment by AnthonyBirot** [comment]
I have a last question. Did you know when the new option of publish will be add in the apt release ?

**Comment by dirk-thomas** [comment]
With the next patch release of this repo. That might be in the next several week but I can't say for sure.

**Pull request merged**
