### PR TITLE
Fix BZip2 inclusion

### PR DESCRIPTION
**Pull request by vrabaud**

### CODE REVIEW

**Comment by vrabaud** [comment]
I have a very specific setup where BZip2 is in its own folder.
The include_dir makes sense. for the _libraries, I am not sure why it worked before while bzip2 was not linked ...

**Comment by dirk-thomas** [comment]
To retrigger the Lunar CI job...

**Comment by dirk-thomas** [comment]
> The include_dir makes sense. for the _libraries, I am not sure why it worked before while bzip2 was not linked

That was actually my first thought too...

**Comment by dirk-thomas** [comment]
Thank you for the patch.

**Pull request merged**
