### PR TITLE
Add timestamp formatting for rosconsole

### PR DESCRIPTION
**Pull request by abrzozowski**
It's an another try to pass a Jenkins build of https://github.com/ros/ros_comm/pull/1533, by rebase origin branch from ros:melodic-devel to ros:neotic-devel.

### CODE REVIEW

**Comment by abrzozowski** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
CI looks ok (~~beside some unrelated flaky tests~~). Please feel free to remove the draft status and close the duplicate PR if you want this one to be reviewed / merged.

**Comment by abrzozowski** [comment]
I closed the duplicate (https://github.com/ros/ros_comm/pull/1533) PR. So, this one is a merge candidate now.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by dirk-thomas** [comment]
@abrzozowski Thanks for the contribution. Please update the documentation in the ROS wiki describing this new feature (as of Noetic) and post a link to the diff here for future readers to find it.

**Comment by abrzozowski** [comment]
@dirk-thomas Thanks for accept changes. There's also a cpp part for this feature https://github.com/ros/rosconsole/pull/22, which should be merged for full support of time formatting.

**Comment by abrzozowski** [comment]
Added description in the ROS wiki: http://wiki.ros.org/action/diff/rosconsole?action=diff&rev1=74&rev2=75

**Pull request merged**
