### PR TITLE
fix log level of RosOutHandler by converting rospy level to expected logging level (#210)

### PR DESCRIPTION
**Pull request by dirk-thomas**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@tfoote @wjwwood Please review and merge.

**Comment by tfoote** [comment]
Is it worth keeping the backwards compatibility of a private variable? If so maybe add a comment on why that's there. 

otherwise +1 for merge

**Comment by dirk-thomas** [comment]
I removed the private variable from the client module.

**Comment by wjwwood** [comment]
+1

**Pull request merged**
